defmodule Google.Ads.Googleads.V4.Enums.ConversionOrAdjustmentLagBucketEnum.ConversionOrAdjustmentLagBucket do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  @type t ::
          integer
          | :UNSPECIFIED
          | :UNKNOWN
          | :CONVERSION_LESS_THAN_ONE_DAY
          | :CONVERSION_ONE_TO_TWO_DAYS
          | :CONVERSION_TWO_TO_THREE_DAYS
          | :CONVERSION_THREE_TO_FOUR_DAYS
          | :CONVERSION_FOUR_TO_FIVE_DAYS
          | :CONVERSION_FIVE_TO_SIX_DAYS
          | :CONVERSION_SIX_TO_SEVEN_DAYS
          | :CONVERSION_SEVEN_TO_EIGHT_DAYS
          | :CONVERSION_EIGHT_TO_NINE_DAYS
          | :CONVERSION_NINE_TO_TEN_DAYS
          | :CONVERSION_TEN_TO_ELEVEN_DAYS
          | :CONVERSION_ELEVEN_TO_TWELVE_DAYS
          | :CONVERSION_TWELVE_TO_THIRTEEN_DAYS
          | :CONVERSION_THIRTEEN_TO_FOURTEEN_DAYS
          | :CONVERSION_FOURTEEN_TO_TWENTY_ONE_DAYS
          | :CONVERSION_TWENTY_ONE_TO_THIRTY_DAYS
          | :CONVERSION_THIRTY_TO_FORTY_FIVE_DAYS
          | :CONVERSION_FORTY_FIVE_TO_SIXTY_DAYS
          | :CONVERSION_SIXTY_TO_NINETY_DAYS
          | :ADJUSTMENT_LESS_THAN_ONE_DAY
          | :ADJUSTMENT_ONE_TO_TWO_DAYS
          | :ADJUSTMENT_TWO_TO_THREE_DAYS
          | :ADJUSTMENT_THREE_TO_FOUR_DAYS
          | :ADJUSTMENT_FOUR_TO_FIVE_DAYS
          | :ADJUSTMENT_FIVE_TO_SIX_DAYS
          | :ADJUSTMENT_SIX_TO_SEVEN_DAYS
          | :ADJUSTMENT_SEVEN_TO_EIGHT_DAYS
          | :ADJUSTMENT_EIGHT_TO_NINE_DAYS
          | :ADJUSTMENT_NINE_TO_TEN_DAYS
          | :ADJUSTMENT_TEN_TO_ELEVEN_DAYS
          | :ADJUSTMENT_ELEVEN_TO_TWELVE_DAYS
          | :ADJUSTMENT_TWELVE_TO_THIRTEEN_DAYS
          | :ADJUSTMENT_THIRTEEN_TO_FOURTEEN_DAYS
          | :ADJUSTMENT_FOURTEEN_TO_TWENTY_ONE_DAYS
          | :ADJUSTMENT_TWENTY_ONE_TO_THIRTY_DAYS
          | :ADJUSTMENT_THIRTY_TO_FORTY_FIVE_DAYS
          | :ADJUSTMENT_FORTY_FIVE_TO_SIXTY_DAYS
          | :ADJUSTMENT_SIXTY_TO_NINETY_DAYS
          | :ADJUSTMENT_NINETY_TO_ONE_HUNDRED_AND_FORTY_FIVE_DAYS
          | :CONVERSION_UNKNOWN
          | :ADJUSTMENT_UNKNOWN

  field :UNSPECIFIED, 0

  field :UNKNOWN, 1

  field :CONVERSION_LESS_THAN_ONE_DAY, 2

  field :CONVERSION_ONE_TO_TWO_DAYS, 3

  field :CONVERSION_TWO_TO_THREE_DAYS, 4

  field :CONVERSION_THREE_TO_FOUR_DAYS, 5

  field :CONVERSION_FOUR_TO_FIVE_DAYS, 6

  field :CONVERSION_FIVE_TO_SIX_DAYS, 7

  field :CONVERSION_SIX_TO_SEVEN_DAYS, 8

  field :CONVERSION_SEVEN_TO_EIGHT_DAYS, 9

  field :CONVERSION_EIGHT_TO_NINE_DAYS, 10

  field :CONVERSION_NINE_TO_TEN_DAYS, 11

  field :CONVERSION_TEN_TO_ELEVEN_DAYS, 12

  field :CONVERSION_ELEVEN_TO_TWELVE_DAYS, 13

  field :CONVERSION_TWELVE_TO_THIRTEEN_DAYS, 14

  field :CONVERSION_THIRTEEN_TO_FOURTEEN_DAYS, 15

  field :CONVERSION_FOURTEEN_TO_TWENTY_ONE_DAYS, 16

  field :CONVERSION_TWENTY_ONE_TO_THIRTY_DAYS, 17

  field :CONVERSION_THIRTY_TO_FORTY_FIVE_DAYS, 18

  field :CONVERSION_FORTY_FIVE_TO_SIXTY_DAYS, 19

  field :CONVERSION_SIXTY_TO_NINETY_DAYS, 20

  field :ADJUSTMENT_LESS_THAN_ONE_DAY, 21

  field :ADJUSTMENT_ONE_TO_TWO_DAYS, 22

  field :ADJUSTMENT_TWO_TO_THREE_DAYS, 23

  field :ADJUSTMENT_THREE_TO_FOUR_DAYS, 24

  field :ADJUSTMENT_FOUR_TO_FIVE_DAYS, 25

  field :ADJUSTMENT_FIVE_TO_SIX_DAYS, 26

  field :ADJUSTMENT_SIX_TO_SEVEN_DAYS, 27

  field :ADJUSTMENT_SEVEN_TO_EIGHT_DAYS, 28

  field :ADJUSTMENT_EIGHT_TO_NINE_DAYS, 29

  field :ADJUSTMENT_NINE_TO_TEN_DAYS, 30

  field :ADJUSTMENT_TEN_TO_ELEVEN_DAYS, 31

  field :ADJUSTMENT_ELEVEN_TO_TWELVE_DAYS, 32

  field :ADJUSTMENT_TWELVE_TO_THIRTEEN_DAYS, 33

  field :ADJUSTMENT_THIRTEEN_TO_FOURTEEN_DAYS, 34

  field :ADJUSTMENT_FOURTEEN_TO_TWENTY_ONE_DAYS, 35

  field :ADJUSTMENT_TWENTY_ONE_TO_THIRTY_DAYS, 36

  field :ADJUSTMENT_THIRTY_TO_FORTY_FIVE_DAYS, 37

  field :ADJUSTMENT_FORTY_FIVE_TO_SIXTY_DAYS, 38

  field :ADJUSTMENT_SIXTY_TO_NINETY_DAYS, 39

  field :ADJUSTMENT_NINETY_TO_ONE_HUNDRED_AND_FORTY_FIVE_DAYS, 40

  field :CONVERSION_UNKNOWN, 41

  field :ADJUSTMENT_UNKNOWN, 42
end

defmodule Google.Ads.Googleads.V4.Enums.ConversionOrAdjustmentLagBucketEnum do
  @moduledoc false
  use Protobuf, syntax: :proto3
  @type t :: %__MODULE__{}

  defstruct []
end
