defmodule Google.Ads.Admanager.V1.Report.TimePeriodColumn do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :TIME_PERIOD_COLUMN_UNSPECIFIED, 0
  field :TIME_PERIOD_COLUMN_DATE, 1
  field :TIME_PERIOD_COLUMN_WEEK, 2
  field :TIME_PERIOD_COLUMN_MONTH, 3
  field :TIME_PERIOD_COLUMN_QUARTER, 4
end

defmodule Google.Ads.Admanager.V1.Report.Dimension do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :DIMENSION_UNSPECIFIED, 0
  field :ADVERTISER_DOMAIN_NAME, 242
  field :ADVERTISER_EXTERNAL_ID, 228
  field :ADVERTISER_ID, 131
  field :ADVERTISER_LABELS, 230
  field :ADVERTISER_LABEL_IDS, 229
  field :ADVERTISER_NAME, 132
  field :ADVERTISER_PRIMARY_CONTACT, 227
  field :AD_LOCATION, 390
  field :AD_LOCATION_NAME, 391
  field :AD_UNIT_CODE, 64
  field :AD_UNIT_CODE_LEVEL_1, 65
  field :AD_UNIT_CODE_LEVEL_10, 74
  field :AD_UNIT_CODE_LEVEL_11, 75
  field :AD_UNIT_CODE_LEVEL_12, 76
  field :AD_UNIT_CODE_LEVEL_13, 77
  field :AD_UNIT_CODE_LEVEL_14, 78
  field :AD_UNIT_CODE_LEVEL_15, 79
  field :AD_UNIT_CODE_LEVEL_16, 80
  field :AD_UNIT_CODE_LEVEL_2, 66
  field :AD_UNIT_CODE_LEVEL_3, 67
  field :AD_UNIT_CODE_LEVEL_4, 68
  field :AD_UNIT_CODE_LEVEL_5, 69
  field :AD_UNIT_CODE_LEVEL_6, 70
  field :AD_UNIT_CODE_LEVEL_7, 71
  field :AD_UNIT_CODE_LEVEL_8, 72
  field :AD_UNIT_CODE_LEVEL_9, 73
  field :AD_UNIT_DEPTH, 101
  field :AD_UNIT_ID, 25
  field :AD_UNIT_ID_ALL_LEVEL, 27
  field :AD_UNIT_ID_LEVEL_1, 30
  field :AD_UNIT_ID_LEVEL_10, 48
  field :AD_UNIT_ID_LEVEL_11, 50
  field :AD_UNIT_ID_LEVEL_12, 52
  field :AD_UNIT_ID_LEVEL_13, 54
  field :AD_UNIT_ID_LEVEL_14, 56
  field :AD_UNIT_ID_LEVEL_15, 58
  field :AD_UNIT_ID_LEVEL_16, 60
  field :AD_UNIT_ID_LEVEL_2, 32
  field :AD_UNIT_ID_LEVEL_3, 34
  field :AD_UNIT_ID_LEVEL_4, 36
  field :AD_UNIT_ID_LEVEL_5, 38
  field :AD_UNIT_ID_LEVEL_6, 40
  field :AD_UNIT_ID_LEVEL_7, 42
  field :AD_UNIT_ID_LEVEL_8, 44
  field :AD_UNIT_ID_LEVEL_9, 46
  field :AD_UNIT_ID_TOP_LEVEL, 142
  field :AD_UNIT_NAME, 26
  field :AD_UNIT_NAME_ALL_LEVEL, 29
  field :AD_UNIT_NAME_LEVEL_1, 31
  field :AD_UNIT_NAME_LEVEL_10, 49
  field :AD_UNIT_NAME_LEVEL_11, 51
  field :AD_UNIT_NAME_LEVEL_12, 53
  field :AD_UNIT_NAME_LEVEL_13, 55
  field :AD_UNIT_NAME_LEVEL_14, 57
  field :AD_UNIT_NAME_LEVEL_15, 59
  field :AD_UNIT_NAME_LEVEL_16, 61
  field :AD_UNIT_NAME_LEVEL_2, 33
  field :AD_UNIT_NAME_LEVEL_3, 35
  field :AD_UNIT_NAME_LEVEL_4, 37
  field :AD_UNIT_NAME_LEVEL_5, 39
  field :AD_UNIT_NAME_LEVEL_6, 41
  field :AD_UNIT_NAME_LEVEL_7, 43
  field :AD_UNIT_NAME_LEVEL_8, 45
  field :AD_UNIT_NAME_LEVEL_9, 47
  field :AD_UNIT_NAME_TOP_LEVEL, 143
  field :AD_UNIT_REWARD_AMOUNT, 63
  field :AD_UNIT_REWARD_TYPE, 62
  field :AD_UNIT_STATUS, 206
  field :AD_UNIT_STATUS_NAME, 207
  field :APP_VERSION, 392
  field :BACKFILL_ADVERTISER_EXTERNAL_ID, 349
  field :BACKFILL_ADVERTISER_ID, 346
  field :BACKFILL_ADVERTISER_LABELS, 351
  field :BACKFILL_ADVERTISER_LABEL_IDS, 350
  field :BACKFILL_ADVERTISER_NAME, 347
  field :BACKFILL_ADVERTISER_PRIMARY_CONTACT, 348
  field :BACKFILL_CREATIVE_BILLING_TYPE, 378
  field :BACKFILL_CREATIVE_BILLING_TYPE_NAME, 379
  field :BACKFILL_CREATIVE_CLICK_THROUGH_URL, 376
  field :BACKFILL_CREATIVE_ID, 370
  field :BACKFILL_CREATIVE_NAME, 371
  field :BACKFILL_CREATIVE_THIRD_PARTY_VENDOR, 377
  field :BACKFILL_CREATIVE_TYPE, 374
  field :BACKFILL_CREATIVE_TYPE_NAME, 375
  field :BACKFILL_LINE_ITEM_ARCHIVED, 278
  field :BACKFILL_LINE_ITEM_COMPANION_DELIVERY_OPTION, 258
  field :BACKFILL_LINE_ITEM_COMPANION_DELIVERY_OPTION_NAME, 259
  field :BACKFILL_LINE_ITEM_COMPUTED_STATUS, 296
  field :BACKFILL_LINE_ITEM_COMPUTED_STATUS_NAME, 297
  field :BACKFILL_LINE_ITEM_CONTRACTED_QUANTITY, 280
  field :BACKFILL_LINE_ITEM_COST_PER_UNIT, 272
  field :BACKFILL_LINE_ITEM_COST_TYPE, 264
  field :BACKFILL_LINE_ITEM_COST_TYPE_NAME, 265
  field :BACKFILL_LINE_ITEM_CREATIVE_END_DATE, 381
  field :BACKFILL_LINE_ITEM_CREATIVE_ROTATION_TYPE, 290
  field :BACKFILL_LINE_ITEM_CREATIVE_ROTATION_TYPE_NAME, 291
  field :BACKFILL_LINE_ITEM_CREATIVE_START_DATE, 380
  field :BACKFILL_LINE_ITEM_CURRENCY_CODE, 288
  field :BACKFILL_LINE_ITEM_DELIVERY_INDICATOR, 274
  field :BACKFILL_LINE_ITEM_DELIVERY_RATE_TYPE, 292
  field :BACKFILL_LINE_ITEM_DELIVERY_RATE_TYPE_NAME, 293
  field :BACKFILL_LINE_ITEM_DISCOUNT_ABSOLUTE, 294
  field :BACKFILL_LINE_ITEM_DISCOUNT_PERCENTAGE, 295
  field :BACKFILL_LINE_ITEM_END_DATE, 267
  field :BACKFILL_LINE_ITEM_END_DATE_TIME, 269
  field :BACKFILL_LINE_ITEM_ENVIRONMENT_TYPE, 302
  field :BACKFILL_LINE_ITEM_ENVIRONMENT_TYPE_NAME, 257
  field :BACKFILL_LINE_ITEM_EXTERNAL_DEAL_ID, 285
  field :BACKFILL_LINE_ITEM_EXTERNAL_ID, 273
  field :BACKFILL_LINE_ITEM_FREQUENCY_CAP, 303
  field :BACKFILL_LINE_ITEM_ID, 298
  field :BACKFILL_LINE_ITEM_LAST_MODIFIED_BY_APP, 289
  field :BACKFILL_LINE_ITEM_LIFETIME_CLICKS, 283
  field :BACKFILL_LINE_ITEM_LIFETIME_IMPRESSIONS, 282
  field :BACKFILL_LINE_ITEM_LIFETIME_VIEWABLE_IMPRESSIONS, 284
  field :BACKFILL_LINE_ITEM_MAKEGOOD, 276
  field :BACKFILL_LINE_ITEM_NAME, 299
  field :BACKFILL_LINE_ITEM_NON_CPD_BOOKED_REVENUE, 286
  field :BACKFILL_LINE_ITEM_OPTIMIZABLE, 277
  field :BACKFILL_LINE_ITEM_PRIMARY_GOAL_TYPE, 262
  field :BACKFILL_LINE_ITEM_PRIMARY_GOAL_TYPE_NAME, 263
  field :BACKFILL_LINE_ITEM_PRIMARY_GOAL_UNIT_TYPE, 260
  field :BACKFILL_LINE_ITEM_PRIMARY_GOAL_UNIT_TYPE_NAME, 261
  field :BACKFILL_LINE_ITEM_PRIORITY, 266
  field :BACKFILL_LINE_ITEM_RESERVATION_STATUS, 306
  field :BACKFILL_LINE_ITEM_RESERVATION_STATUS_NAME, 307
  field :BACKFILL_LINE_ITEM_START_DATE, 268
  field :BACKFILL_LINE_ITEM_START_DATE_TIME, 270
  field :BACKFILL_LINE_ITEM_TYPE, 300
  field :BACKFILL_LINE_ITEM_TYPE_NAME, 301
  field :BACKFILL_LINE_ITEM_UNLIMITED_END, 271
  field :BACKFILL_LINE_ITEM_VALUE_COST_PER_UNIT, 275
  field :BACKFILL_LINE_ITEM_WEB_PROPERTY_CODE, 287
  field :BACKFILL_MASTER_COMPANION_CREATIVE_ID, 372
  field :BACKFILL_MASTER_COMPANION_CREATIVE_NAME, 373
  field :BACKFILL_ORDER_AGENCY, 313
  field :BACKFILL_ORDER_AGENCY_ID, 314
  field :BACKFILL_ORDER_BOOKED_CPC, 315
  field :BACKFILL_ORDER_BOOKED_CPM, 316
  field :BACKFILL_ORDER_DELIVERY_STATUS, 340
  field :BACKFILL_ORDER_DELIVERY_STATUS_NAME, 341
  field :BACKFILL_ORDER_END_DATE, 317
  field :BACKFILL_ORDER_END_DATE_TIME, 319
  field :BACKFILL_ORDER_EXTERNAL_ID, 320
  field :BACKFILL_ORDER_ID, 338
  field :BACKFILL_ORDER_LABELS, 334
  field :BACKFILL_ORDER_LABEL_IDS, 335
  field :BACKFILL_ORDER_LIFETIME_CLICKS, 322
  field :BACKFILL_ORDER_LIFETIME_IMPRESSIONS, 323
  field :BACKFILL_ORDER_NAME, 339
  field :BACKFILL_ORDER_PO_NUMBER, 324
  field :BACKFILL_ORDER_PROGRAMMATIC, 321
  field :BACKFILL_ORDER_SALESPERSON, 325
  field :BACKFILL_ORDER_SECONDARY_SALESPEOPLE, 329
  field :BACKFILL_ORDER_SECONDARY_SALESPEOPLE_ID, 328
  field :BACKFILL_ORDER_SECONDARY_TRAFFICKERS, 331
  field :BACKFILL_ORDER_SECONDARY_TRAFFICKERS_ID, 330
  field :BACKFILL_ORDER_START_DATE, 332
  field :BACKFILL_ORDER_START_DATE_TIME, 333
  field :BACKFILL_ORDER_TRAFFICKER, 326
  field :BACKFILL_ORDER_TRAFFICKER_ID, 327
  field :BACKFILL_ORDER_UNLIMITED_END, 318
  field :BACKFILL_PROGRAMMATIC_BUYER_ID, 336
  field :BACKFILL_PROGRAMMATIC_BUYER_NAME, 337
  field :BRANDING_TYPE, 383
  field :BRANDING_TYPE_NAME, 384
  field :BROWSER_CATEGORY, 119
  field :BROWSER_CATEGORY_NAME, 120
  field :BROWSER_ID, 235
  field :BROWSER_NAME, 236
  field :CARRIER_ID, 369
  field :CARRIER_NAME, 368
  field :CLASSIFIED_ADVERTISER_ID, 133
  field :CLASSIFIED_ADVERTISER_NAME, 134
  field :CLASSIFIED_BRAND_ID, 243
  field :CLASSIFIED_BRAND_NAME, 244
  field :CONTENT_ID, 246
  field :CONTENT_NAME, 247
  field :COUNTRY_ID, 11
  field :COUNTRY_NAME, 12
  field :CREATIVE_BILLING_TYPE, 366
  field :CREATIVE_BILLING_TYPE_NAME, 367
  field :CREATIVE_CLICK_THROUGH_URL, 174
  field :CREATIVE_ID, 138
  field :CREATIVE_NAME, 139
  field :CREATIVE_TECHNOLOGY, 148
  field :CREATIVE_TECHNOLOGY_NAME, 149
  field :CREATIVE_THIRD_PARTY_VENDOR, 361
  field :CREATIVE_TYPE, 344
  field :CREATIVE_TYPE_NAME, 345
  field :DATE, 3
  field :DAY_OF_WEEK, 4
  field :DEMAND_CHANNEL, 9
  field :DEMAND_CHANNEL_NAME, 10
  field :DEMAND_SUBCHANNEL, 22
  field :DEMAND_SUBCHANNEL_NAME, 23
  field :DEVICE, 226
  field :DEVICE_CATEGORY, 15
  field :DEVICE_CATEGORY_NAME, 16
  field :DEVICE_NAME, 225
  field :EXCHANGE_THIRD_PARTY_COMPANY_ID, 185
  field :EXCHANGE_THIRD_PARTY_COMPANY_NAME, 186
  field :FIRST_LOOK_PRICING_RULE_ID, 248
  field :FIRST_LOOK_PRICING_RULE_NAME, 249
  field :HOUR, 100
  field :INTERACTION_TYPE, 223
  field :INTERACTION_TYPE_NAME, 224
  field :INVENTORY_FORMAT, 17
  field :INVENTORY_FORMAT_NAME, 18
  field :INVENTORY_TYPE, 19
  field :INVENTORY_TYPE_NAME, 20
  field :IS_ADX_DIRECT, 382
  field :IS_FIRST_LOOK_DEAL, 401
  field :KEY_VALUES_ID, 214
  field :KEY_VALUES_NAME, 215
  field :LINE_ITEM_ARCHIVED, 188
  field :LINE_ITEM_COMPANION_DELIVERY_OPTION, 204
  field :LINE_ITEM_COMPANION_DELIVERY_OPTION_NAME, 205
  field :LINE_ITEM_COMPUTED_STATUS, 250
  field :LINE_ITEM_COMPUTED_STATUS_NAME, 251
  field :LINE_ITEM_CONTRACTED_QUANTITY, 92
  field :LINE_ITEM_COST_PER_UNIT, 85
  field :LINE_ITEM_COST_TYPE, 212
  field :LINE_ITEM_COST_TYPE_NAME, 213
  field :LINE_ITEM_CREATIVE_END_DATE, 176
  field :LINE_ITEM_CREATIVE_ROTATION_TYPE, 189
  field :LINE_ITEM_CREATIVE_ROTATION_TYPE_NAME, 190
  field :LINE_ITEM_CREATIVE_START_DATE, 175
  field :LINE_ITEM_CURRENCY_CODE, 180
  field :LINE_ITEM_DELIVERY_INDICATOR, 87
  field :LINE_ITEM_DELIVERY_RATE_TYPE, 191
  field :LINE_ITEM_DELIVERY_RATE_TYPE_NAME, 192
  field :LINE_ITEM_DISCOUNT_ABSOLUTE, 195
  field :LINE_ITEM_DISCOUNT_PERCENTAGE, 196
  field :LINE_ITEM_END_DATE, 81
  field :LINE_ITEM_END_DATE_TIME, 83
  field :LINE_ITEM_ENVIRONMENT_TYPE, 201
  field :LINE_ITEM_ENVIRONMENT_TYPE_NAME, 202
  field :LINE_ITEM_EXTERNAL_DEAL_ID, 97
  field :LINE_ITEM_EXTERNAL_ID, 86
  field :LINE_ITEM_FREQUENCY_CAP, 256
  field :LINE_ITEM_ID, 1
  field :LINE_ITEM_LAST_MODIFIED_BY_APP, 181
  field :LINE_ITEM_LIFETIME_CLICKS, 95
  field :LINE_ITEM_LIFETIME_IMPRESSIONS, 94
  field :LINE_ITEM_LIFETIME_VIEWABLE_IMPRESSIONS, 96
  field :LINE_ITEM_MAKEGOOD, 89
  field :LINE_ITEM_NAME, 2
  field :LINE_ITEM_NON_CPD_BOOKED_REVENUE, 98
  field :LINE_ITEM_OPTIMIZABLE, 90
  field :LINE_ITEM_PRIMARY_GOAL_TYPE, 210
  field :LINE_ITEM_PRIMARY_GOAL_TYPE_NAME, 211
  field :LINE_ITEM_PRIMARY_GOAL_UNITS_ABSOLUTE, 93
  field :LINE_ITEM_PRIMARY_GOAL_UNITS_PERCENTAGE, 396
  field :LINE_ITEM_PRIMARY_GOAL_UNIT_TYPE, 208
  field :LINE_ITEM_PRIMARY_GOAL_UNIT_TYPE_NAME, 209
  field :LINE_ITEM_PRIORITY, 24
  field :LINE_ITEM_RESERVATION_STATUS, 304
  field :LINE_ITEM_RESERVATION_STATUS_NAME, 305
  field :LINE_ITEM_START_DATE, 82
  field :LINE_ITEM_START_DATE_TIME, 84
  field :LINE_ITEM_TYPE, 193
  field :LINE_ITEM_TYPE_NAME, 194
  field :LINE_ITEM_UNLIMITED_END, 187
  field :LINE_ITEM_VALUE_COST_PER_UNIT, 88
  field :LINE_ITEM_WEB_PROPERTY_CODE, 179
  field :MASTER_COMPANION_CREATIVE_ID, 140
  field :MASTER_COMPANION_CREATIVE_NAME, 141
  field :MOBILE_APP_FREE, 128
  field :MOBILE_APP_ICON_URL, 129
  field :MOBILE_APP_ID, 123
  field :MOBILE_APP_NAME, 127
  field :MOBILE_APP_OWNERSHIP_STATUS, 311
  field :MOBILE_APP_OWNERSHIP_STATUS_NAME, 312
  field :MOBILE_APP_STORE, 125
  field :MOBILE_APP_STORE_NAME, 245
  field :MOBILE_INVENTORY_TYPE, 99
  field :MOBILE_INVENTORY_TYPE_NAME, 21
  field :MOBILE_SDK_VERSION_NAME, 130
  field :MONTH_YEAR, 6
  field :NATIVE_AD_FORMAT_ID, 255
  field :NATIVE_AD_FORMAT_NAME, 254
  field :NATIVE_STYLE_ID, 253
  field :NATIVE_STYLE_NAME, 252
  field :OPERATING_SYSTEM_CATEGORY, 117
  field :OPERATING_SYSTEM_CATEGORY_NAME, 118
  field :OPERATING_SYSTEM_VERSION_ID, 238
  field :OPERATING_SYSTEM_VERSION_NAME, 237
  field :ORDER_AGENCY, 150
  field :ORDER_AGENCY_ID, 151
  field :ORDER_BOOKED_CPC, 152
  field :ORDER_BOOKED_CPM, 153
  field :ORDER_DELIVERY_STATUS, 231
  field :ORDER_DELIVERY_STATUS_NAME, 239
  field :ORDER_END_DATE, 154
  field :ORDER_END_DATE_TIME, 155
  field :ORDER_EXTERNAL_ID, 156
  field :ORDER_ID, 7
  field :ORDER_LABELS, 170
  field :ORDER_LABEL_IDS, 171
  field :ORDER_LIFETIME_CLICKS, 158
  field :ORDER_LIFETIME_IMPRESSIONS, 159
  field :ORDER_NAME, 8
  field :ORDER_PO_NUMBER, 160
  field :ORDER_PROGRAMMATIC, 157
  field :ORDER_SALESPERSON, 161
  field :ORDER_SECONDARY_SALESPEOPLE, 164
  field :ORDER_SECONDARY_SALESPEOPLE_ID, 165
  field :ORDER_SECONDARY_TRAFFICKERS, 166
  field :ORDER_SECONDARY_TRAFFICKERS_ID, 167
  field :ORDER_START_DATE, 168
  field :ORDER_START_DATE_TIME, 169
  field :ORDER_TRAFFICKER, 162
  field :ORDER_TRAFFICKER_ID, 163
  field :ORDER_UNLIMITED_END, 203
  field :PLACEMENT_ID, 113
  field :PLACEMENT_ID_ALL, 144
  field :PLACEMENT_NAME, 114
  field :PLACEMENT_NAME_ALL, 145
  field :PLACEMENT_STATUS, 362
  field :PLACEMENT_STATUS_ALL, 363
  field :PLACEMENT_STATUS_NAME, 364
  field :PLACEMENT_STATUS_NAME_ALL, 365
  field :PROGRAMMATIC_BUYER_ID, 240
  field :PROGRAMMATIC_BUYER_NAME, 241
  field :PROGRAMMATIC_CHANNEL, 13
  field :PROGRAMMATIC_CHANNEL_NAME, 14
  field :RENDERED_CREATIVE_SIZE, 343
  field :REQUESTED_AD_SIZES, 352
  field :REQUEST_TYPE, 146
  field :REQUEST_TYPE_NAME, 147
  field :SITE, 387
  field :TARGETING_ID, 232
  field :TARGETING_NAME, 233
  field :TARGETING_TYPE, 385
  field :TARGETING_TYPE_NAME, 386
  field :TRAFFIC_SOURCE, 388
  field :TRAFFIC_SOURCE_NAME, 389
  field :UNIFIED_PRICING_RULE_ID, 393
  field :UNIFIED_PRICING_RULE_NAME, 394
  field :VIDEO_PLCMT, 172
  field :VIDEO_PLCMT_NAME, 173
  field :WEEK, 5
  field :YIELD_GROUP_BUYER_NAME, 184
  field :YIELD_GROUP_ID, 182
  field :YIELD_GROUP_NAME, 183
  field :LINE_ITEM_CUSTOM_FIELD_0_OPTION_ID, 10000
  field :LINE_ITEM_CUSTOM_FIELD_1_OPTION_ID, 10001
  field :LINE_ITEM_CUSTOM_FIELD_2_OPTION_ID, 10002
  field :LINE_ITEM_CUSTOM_FIELD_3_OPTION_ID, 10003
  field :LINE_ITEM_CUSTOM_FIELD_4_OPTION_ID, 10004
  field :LINE_ITEM_CUSTOM_FIELD_5_OPTION_ID, 10005
  field :LINE_ITEM_CUSTOM_FIELD_6_OPTION_ID, 10006
  field :LINE_ITEM_CUSTOM_FIELD_7_OPTION_ID, 10007
  field :LINE_ITEM_CUSTOM_FIELD_8_OPTION_ID, 10008
  field :LINE_ITEM_CUSTOM_FIELD_9_OPTION_ID, 10009
  field :LINE_ITEM_CUSTOM_FIELD_10_OPTION_ID, 10010
  field :LINE_ITEM_CUSTOM_FIELD_11_OPTION_ID, 10011
  field :LINE_ITEM_CUSTOM_FIELD_12_OPTION_ID, 10012
  field :LINE_ITEM_CUSTOM_FIELD_13_OPTION_ID, 10013
  field :LINE_ITEM_CUSTOM_FIELD_14_OPTION_ID, 10014
  field :LINE_ITEM_CUSTOM_FIELD_0_VALUE, 11000
  field :LINE_ITEM_CUSTOM_FIELD_1_VALUE, 11001
  field :LINE_ITEM_CUSTOM_FIELD_2_VALUE, 11002
  field :LINE_ITEM_CUSTOM_FIELD_3_VALUE, 11003
  field :LINE_ITEM_CUSTOM_FIELD_4_VALUE, 11004
  field :LINE_ITEM_CUSTOM_FIELD_5_VALUE, 11005
  field :LINE_ITEM_CUSTOM_FIELD_6_VALUE, 11006
  field :LINE_ITEM_CUSTOM_FIELD_7_VALUE, 11007
  field :LINE_ITEM_CUSTOM_FIELD_8_VALUE, 11008
  field :LINE_ITEM_CUSTOM_FIELD_9_VALUE, 11009
  field :LINE_ITEM_CUSTOM_FIELD_10_VALUE, 11010
  field :LINE_ITEM_CUSTOM_FIELD_11_VALUE, 11011
  field :LINE_ITEM_CUSTOM_FIELD_12_VALUE, 11012
  field :LINE_ITEM_CUSTOM_FIELD_13_VALUE, 11013
  field :LINE_ITEM_CUSTOM_FIELD_14_VALUE, 11014
  field :ORDER_CUSTOM_FIELD_0_OPTION_ID, 12000
  field :ORDER_CUSTOM_FIELD_1_OPTION_ID, 12001
  field :ORDER_CUSTOM_FIELD_2_OPTION_ID, 12002
  field :ORDER_CUSTOM_FIELD_3_OPTION_ID, 12003
  field :ORDER_CUSTOM_FIELD_4_OPTION_ID, 12004
  field :ORDER_CUSTOM_FIELD_5_OPTION_ID, 12005
  field :ORDER_CUSTOM_FIELD_6_OPTION_ID, 12006
  field :ORDER_CUSTOM_FIELD_7_OPTION_ID, 12007
  field :ORDER_CUSTOM_FIELD_8_OPTION_ID, 12008
  field :ORDER_CUSTOM_FIELD_9_OPTION_ID, 12009
  field :ORDER_CUSTOM_FIELD_10_OPTION_ID, 12010
  field :ORDER_CUSTOM_FIELD_11_OPTION_ID, 12011
  field :ORDER_CUSTOM_FIELD_12_OPTION_ID, 12012
  field :ORDER_CUSTOM_FIELD_13_OPTION_ID, 12013
  field :ORDER_CUSTOM_FIELD_14_OPTION_ID, 12014
  field :ORDER_CUSTOM_FIELD_0_VALUE, 13000
  field :ORDER_CUSTOM_FIELD_1_VALUE, 13001
  field :ORDER_CUSTOM_FIELD_2_VALUE, 13002
  field :ORDER_CUSTOM_FIELD_3_VALUE, 13003
  field :ORDER_CUSTOM_FIELD_4_VALUE, 13004
  field :ORDER_CUSTOM_FIELD_5_VALUE, 13005
  field :ORDER_CUSTOM_FIELD_6_VALUE, 13006
  field :ORDER_CUSTOM_FIELD_7_VALUE, 13007
  field :ORDER_CUSTOM_FIELD_8_VALUE, 13008
  field :ORDER_CUSTOM_FIELD_9_VALUE, 13009
  field :ORDER_CUSTOM_FIELD_10_VALUE, 13010
  field :ORDER_CUSTOM_FIELD_11_VALUE, 13011
  field :ORDER_CUSTOM_FIELD_12_VALUE, 13012
  field :ORDER_CUSTOM_FIELD_13_VALUE, 13013
  field :ORDER_CUSTOM_FIELD_14_VALUE, 13014
  field :CREATIVE_CUSTOM_FIELD_0_OPTION_ID, 14000
  field :CREATIVE_CUSTOM_FIELD_1_OPTION_ID, 14001
  field :CREATIVE_CUSTOM_FIELD_2_OPTION_ID, 14002
  field :CREATIVE_CUSTOM_FIELD_3_OPTION_ID, 14003
  field :CREATIVE_CUSTOM_FIELD_4_OPTION_ID, 14004
  field :CREATIVE_CUSTOM_FIELD_5_OPTION_ID, 14005
  field :CREATIVE_CUSTOM_FIELD_6_OPTION_ID, 14006
  field :CREATIVE_CUSTOM_FIELD_7_OPTION_ID, 14007
  field :CREATIVE_CUSTOM_FIELD_8_OPTION_ID, 14008
  field :CREATIVE_CUSTOM_FIELD_9_OPTION_ID, 14009
  field :CREATIVE_CUSTOM_FIELD_10_OPTION_ID, 14010
  field :CREATIVE_CUSTOM_FIELD_11_OPTION_ID, 14011
  field :CREATIVE_CUSTOM_FIELD_12_OPTION_ID, 14012
  field :CREATIVE_CUSTOM_FIELD_13_OPTION_ID, 14013
  field :CREATIVE_CUSTOM_FIELD_14_OPTION_ID, 14014
  field :CREATIVE_CUSTOM_FIELD_0_VALUE, 15000
  field :CREATIVE_CUSTOM_FIELD_1_VALUE, 15001
  field :CREATIVE_CUSTOM_FIELD_2_VALUE, 15002
  field :CREATIVE_CUSTOM_FIELD_3_VALUE, 15003
  field :CREATIVE_CUSTOM_FIELD_4_VALUE, 15004
  field :CREATIVE_CUSTOM_FIELD_5_VALUE, 15005
  field :CREATIVE_CUSTOM_FIELD_6_VALUE, 15006
  field :CREATIVE_CUSTOM_FIELD_7_VALUE, 15007
  field :CREATIVE_CUSTOM_FIELD_8_VALUE, 15008
  field :CREATIVE_CUSTOM_FIELD_9_VALUE, 15009
  field :CREATIVE_CUSTOM_FIELD_10_VALUE, 15010
  field :CREATIVE_CUSTOM_FIELD_11_VALUE, 15011
  field :CREATIVE_CUSTOM_FIELD_12_VALUE, 15012
  field :CREATIVE_CUSTOM_FIELD_13_VALUE, 15013
  field :CREATIVE_CUSTOM_FIELD_14_VALUE, 15014
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_0_OPTION_ID, 16000
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_1_OPTION_ID, 16001
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_2_OPTION_ID, 16002
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_3_OPTION_ID, 16003
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_4_OPTION_ID, 16004
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_5_OPTION_ID, 16005
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_6_OPTION_ID, 16006
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_7_OPTION_ID, 16007
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_8_OPTION_ID, 16008
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_9_OPTION_ID, 16009
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_10_OPTION_ID, 16010
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_11_OPTION_ID, 16011
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_12_OPTION_ID, 16012
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_13_OPTION_ID, 16013
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_14_OPTION_ID, 16014
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_0_VALUE, 17000
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_1_VALUE, 17001
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_2_VALUE, 17002
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_3_VALUE, 17003
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_4_VALUE, 17004
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_5_VALUE, 17005
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_6_VALUE, 17006
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_7_VALUE, 17007
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_8_VALUE, 17008
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_9_VALUE, 17009
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_10_VALUE, 17010
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_11_VALUE, 17011
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_12_VALUE, 17012
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_13_VALUE, 17013
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_14_VALUE, 17014
  field :BACKFILL_ORDER_CUSTOM_FIELD_0_OPTION_ID, 18000
  field :BACKFILL_ORDER_CUSTOM_FIELD_1_OPTION_ID, 18001
  field :BACKFILL_ORDER_CUSTOM_FIELD_2_OPTION_ID, 18002
  field :BACKFILL_ORDER_CUSTOM_FIELD_3_OPTION_ID, 18003
  field :BACKFILL_ORDER_CUSTOM_FIELD_4_OPTION_ID, 18004
  field :BACKFILL_ORDER_CUSTOM_FIELD_5_OPTION_ID, 18005
  field :BACKFILL_ORDER_CUSTOM_FIELD_6_OPTION_ID, 18006
  field :BACKFILL_ORDER_CUSTOM_FIELD_7_OPTION_ID, 18007
  field :BACKFILL_ORDER_CUSTOM_FIELD_8_OPTION_ID, 18008
  field :BACKFILL_ORDER_CUSTOM_FIELD_9_OPTION_ID, 18009
  field :BACKFILL_ORDER_CUSTOM_FIELD_10_OPTION_ID, 18010
  field :BACKFILL_ORDER_CUSTOM_FIELD_11_OPTION_ID, 18011
  field :BACKFILL_ORDER_CUSTOM_FIELD_12_OPTION_ID, 18012
  field :BACKFILL_ORDER_CUSTOM_FIELD_13_OPTION_ID, 18013
  field :BACKFILL_ORDER_CUSTOM_FIELD_14_OPTION_ID, 18014
  field :BACKFILL_ORDER_CUSTOM_FIELD_0_VALUE, 19000
  field :BACKFILL_ORDER_CUSTOM_FIELD_1_VALUE, 19001
  field :BACKFILL_ORDER_CUSTOM_FIELD_2_VALUE, 19002
  field :BACKFILL_ORDER_CUSTOM_FIELD_3_VALUE, 19003
  field :BACKFILL_ORDER_CUSTOM_FIELD_4_VALUE, 19004
  field :BACKFILL_ORDER_CUSTOM_FIELD_5_VALUE, 19005
  field :BACKFILL_ORDER_CUSTOM_FIELD_6_VALUE, 19006
  field :BACKFILL_ORDER_CUSTOM_FIELD_7_VALUE, 19007
  field :BACKFILL_ORDER_CUSTOM_FIELD_8_VALUE, 19008
  field :BACKFILL_ORDER_CUSTOM_FIELD_9_VALUE, 19009
  field :BACKFILL_ORDER_CUSTOM_FIELD_10_VALUE, 19010
  field :BACKFILL_ORDER_CUSTOM_FIELD_11_VALUE, 19011
  field :BACKFILL_ORDER_CUSTOM_FIELD_12_VALUE, 19012
  field :BACKFILL_ORDER_CUSTOM_FIELD_13_VALUE, 19013
  field :BACKFILL_ORDER_CUSTOM_FIELD_14_VALUE, 19014
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_0_OPTION_ID, 20000
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_1_OPTION_ID, 20001
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_2_OPTION_ID, 20002
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_3_OPTION_ID, 20003
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_4_OPTION_ID, 20004
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_5_OPTION_ID, 20005
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_6_OPTION_ID, 20006
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_7_OPTION_ID, 20007
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_8_OPTION_ID, 20008
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_9_OPTION_ID, 20009
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_10_OPTION_ID, 20010
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_11_OPTION_ID, 20011
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_12_OPTION_ID, 20012
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_13_OPTION_ID, 20013
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_14_OPTION_ID, 20014
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_0_VALUE, 21000
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_1_VALUE, 21001
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_2_VALUE, 21002
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_3_VALUE, 21003
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_4_VALUE, 21004
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_5_VALUE, 21005
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_6_VALUE, 21006
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_7_VALUE, 21007
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_8_VALUE, 21008
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_9_VALUE, 21009
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_10_VALUE, 21010
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_11_VALUE, 21011
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_12_VALUE, 21012
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_13_VALUE, 21013
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_14_VALUE, 21014
  field :CUSTOM_DIMENSION_0_VALUE_ID, 100_000
  field :CUSTOM_DIMENSION_1_VALUE_ID, 100_001
  field :CUSTOM_DIMENSION_2_VALUE_ID, 100_002
  field :CUSTOM_DIMENSION_3_VALUE_ID, 100_003
  field :CUSTOM_DIMENSION_4_VALUE_ID, 100_004
  field :CUSTOM_DIMENSION_5_VALUE_ID, 100_005
  field :CUSTOM_DIMENSION_6_VALUE_ID, 100_006
  field :CUSTOM_DIMENSION_7_VALUE_ID, 100_007
  field :CUSTOM_DIMENSION_8_VALUE_ID, 100_008
  field :CUSTOM_DIMENSION_9_VALUE_ID, 100_009
  field :CUSTOM_DIMENSION_0_VALUE, 101_000
  field :CUSTOM_DIMENSION_1_VALUE, 101_001
  field :CUSTOM_DIMENSION_2_VALUE, 101_002
  field :CUSTOM_DIMENSION_3_VALUE, 101_003
  field :CUSTOM_DIMENSION_4_VALUE, 101_004
  field :CUSTOM_DIMENSION_5_VALUE, 101_005
  field :CUSTOM_DIMENSION_6_VALUE, 101_006
  field :CUSTOM_DIMENSION_7_VALUE, 101_007
  field :CUSTOM_DIMENSION_8_VALUE, 101_008
  field :CUSTOM_DIMENSION_9_VALUE, 101_009
end

defmodule Google.Ads.Admanager.V1.Report.Metric do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :METRIC_UNSPECIFIED, 0
  field :ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME, 61
  field :ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS, 58
  field :ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, 57
  field :ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_RATE, 60
  field :ACTIVE_VIEW_VIEWABLE_IMPRESSIONS, 56
  field :ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_RATE, 59
  field :ADSENSE_ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME, 73
  field :ADSENSE_ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS, 70
  field :ADSENSE_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, 69
  field :ADSENSE_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_RATE, 72
  field :ADSENSE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS, 68
  field :ADSENSE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_RATE, 71
  field :ADSENSE_AVERAGE_ECPM, 26
  field :ADSENSE_CLICKS, 23
  field :ADSENSE_CTR, 24
  field :ADSENSE_IMPRESSIONS, 22
  field :ADSENSE_PERCENT_CLICKS, 28
  field :ADSENSE_PERCENT_IMPRESSIONS, 27
  field :ADSENSE_PERCENT_REVENUE, 29
  field :ADSENSE_PERCENT_REVENUE_WITHOUT_CPD, 30
  field :ADSENSE_RESPONSES_SERVED, 41
  field :ADSENSE_REVENUE, 25
  field :AD_EXCHANGE_ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME, 79
  field :AD_EXCHANGE_ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS, 76
  field :AD_EXCHANGE_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, 75
  field :AD_EXCHANGE_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_RATE, 78
  field :AD_EXCHANGE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS, 74
  field :AD_EXCHANGE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_RATE, 77
  field :AD_EXCHANGE_AVERAGE_ECPM, 18
  field :AD_EXCHANGE_CLICKS, 15
  field :AD_EXCHANGE_CTR, 16
  field :AD_EXCHANGE_IMPRESSIONS, 14
  field :AD_EXCHANGE_PERCENT_CLICKS, 20
  field :AD_EXCHANGE_PERCENT_IMPRESSIONS, 19
  field :AD_EXCHANGE_PERCENT_REVENUE, 21
  field :AD_EXCHANGE_PERCENT_REVENUE_WITHOUT_CPD, 31
  field :AD_EXCHANGE_RESPONSES_SERVED, 42
  field :AD_EXCHANGE_REVENUE, 17
  field :AD_REQUESTS, 38
  field :AD_SERVER_ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME, 67
  field :AD_SERVER_ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS, 64
  field :AD_SERVER_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, 63
  field :AD_SERVER_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_RATE, 66
  field :AD_SERVER_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS, 62
  field :AD_SERVER_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_RATE, 65
  field :AD_SERVER_AVERAGE_ECPM, 34
  field :AD_SERVER_AVERAGE_ECPM_WITHOUT_CPD, 10
  field :AD_SERVER_CLICKS, 7
  field :AD_SERVER_CPD_REVENUE, 32
  field :AD_SERVER_CTR, 8
  field :AD_SERVER_IMPRESSIONS, 6
  field :AD_SERVER_PERCENT_CLICKS, 12
  field :AD_SERVER_PERCENT_IMPRESSIONS, 11
  field :AD_SERVER_PERCENT_REVENUE, 35
  field :AD_SERVER_PERCENT_REVENUE_WITHOUT_CPD, 13
  field :AD_SERVER_RESPONSES_SERVED, 40
  field :AD_SERVER_REVENUE, 33
  field :AD_SERVER_REVENUE_WITHOUT_CPD, 9
  field :AUCTIONS_WON, 80
  field :AVERAGE_ECPM, 37
  field :AVERAGE_ECPM_WITHOUT_CPD, 5
  field :BIDS, 81
  field :BIDS_IN_AUCTION, 82
  field :CALLOUTS, 83
  field :CLICKS, 2
  field :CODE_SERVED_COUNT, 44
  field :CTR, 3
  field :GOOGLE_SOLD_AUCTION_COVIEWED_IMPRESSIONS, 129
  field :GOOGLE_SOLD_AUCTION_IMPRESSIONS, 128
  field :GOOGLE_SOLD_COVIEWED_IMPRESSIONS, 131
  field :GOOGLE_SOLD_IMPRESSIONS, 130
  field :GOOGLE_SOLD_RESERVATION_COVIEWED_IMPRESSIONS, 127
  field :GOOGLE_SOLD_RESERVATION_IMPRESSIONS, 126
  field :IMPRESSIONS, 1
  field :PARTNER_SALES_FILLED_POD_REQUESTS, 135
  field :PARTNER_SALES_FILL_RATE, 136
  field :PARTNER_SALES_PARTNER_MATCH_RATE, 137
  field :PARTNER_SALES_QUERIES, 132
  field :PARTNER_SALES_UNFILLED_IMPRESSIONS, 133
  field :PARTNER_SALES_UNMATCHED_QUERIES, 134
  field :PARTNER_SOLD_CODE_SERVED, 125
  field :PARTNER_SOLD_COVIEWED_IMPRESSIONS, 124
  field :PARTNER_SOLD_IMPRESSIONS, 123
  field :PROGRAMMATIC_ELIGIBLE_AD_REQUESTS, 177
  field :PROGRAMMATIC_MATCH_RATE, 178
  field :PROGRAMMATIC_RESPONSES_SERVED, 176
  field :RESPONSES_SERVED, 39
  field :REVENUE, 36
  field :REVENUE_WITHOUT_CPD, 4
  field :SUCCESSFUL_RESPONSES, 84
  field :UNFILLED_IMPRESSIONS, 45
  field :UNMATCHED_AD_REQUESTS, 43
  field :USER_MESSAGES_OFFERWALL_MESSAGES_SHOWN, 121
  field :USER_MESSAGES_OFFERWALL_SUCCESSFUL_ENGAGEMENTS, 122
  field :VIDEO_INTERACTION_AVERAGE_INTERACTION_RATE, 92
  field :VIDEO_INTERACTION_COLLAPSES, 93
  field :VIDEO_INTERACTION_EXPANDS, 95
  field :VIDEO_INTERACTION_FULL_SCREENS, 96
  field :VIDEO_INTERACTION_MUTES, 97
  field :VIDEO_INTERACTION_PAUSES, 98
  field :VIDEO_INTERACTION_RESUMES, 99
  field :VIDEO_INTERACTION_REWINDS, 100
  field :VIDEO_INTERACTION_UNMUTES, 101
  field :VIDEO_INTERACTION_VIDEO_SKIPS, 102
  field :VIDEO_REAL_TIME_CREATIVE_SERVES, 139
  field :VIDEO_REAL_TIME_ERROR_100_COUNT, 143
  field :VIDEO_REAL_TIME_ERROR_101_COUNT, 144
  field :VIDEO_REAL_TIME_ERROR_102_COUNT, 145
  field :VIDEO_REAL_TIME_ERROR_200_COUNT, 146
  field :VIDEO_REAL_TIME_ERROR_201_COUNT, 147
  field :VIDEO_REAL_TIME_ERROR_202_COUNT, 148
  field :VIDEO_REAL_TIME_ERROR_203_COUNT, 149
  field :VIDEO_REAL_TIME_ERROR_300_COUNT, 150
  field :VIDEO_REAL_TIME_ERROR_301_COUNT, 151
  field :VIDEO_REAL_TIME_ERROR_302_COUNT, 152
  field :VIDEO_REAL_TIME_ERROR_303_COUNT, 153
  field :VIDEO_REAL_TIME_ERROR_400_COUNT, 154
  field :VIDEO_REAL_TIME_ERROR_401_COUNT, 155
  field :VIDEO_REAL_TIME_ERROR_402_COUNT, 156
  field :VIDEO_REAL_TIME_ERROR_403_COUNT, 157
  field :VIDEO_REAL_TIME_ERROR_405_COUNT, 158
  field :VIDEO_REAL_TIME_ERROR_406_COUNT, 159
  field :VIDEO_REAL_TIME_ERROR_407_COUNT, 160
  field :VIDEO_REAL_TIME_ERROR_408_COUNT, 161
  field :VIDEO_REAL_TIME_ERROR_409_COUNT, 162
  field :VIDEO_REAL_TIME_ERROR_410_COUNT, 163
  field :VIDEO_REAL_TIME_ERROR_500_COUNT, 164
  field :VIDEO_REAL_TIME_ERROR_501_COUNT, 165
  field :VIDEO_REAL_TIME_ERROR_502_COUNT, 166
  field :VIDEO_REAL_TIME_ERROR_503_COUNT, 167
  field :VIDEO_REAL_TIME_ERROR_600_COUNT, 168
  field :VIDEO_REAL_TIME_ERROR_601_COUNT, 169
  field :VIDEO_REAL_TIME_ERROR_602_COUNT, 170
  field :VIDEO_REAL_TIME_ERROR_603_COUNT, 171
  field :VIDEO_REAL_TIME_ERROR_604_COUNT, 172
  field :VIDEO_REAL_TIME_ERROR_900_COUNT, 173
  field :VIDEO_REAL_TIME_ERROR_901_COUNT, 174
  field :VIDEO_REAL_TIME_IMPRESSIONS, 138
  field :VIDEO_REAL_TIME_MATCHED_QUERIES, 140
  field :VIDEO_REAL_TIME_TOTAL_ERROR_COUNT, 175
  field :VIDEO_REAL_TIME_TOTAL_QUERIES, 142
  field :VIDEO_REAL_TIME_UNMATCHED_QUERIES, 141
  field :VIDEO_VIEWERSHIP_AUTO_PLAYS, 103
  field :VIDEO_VIEWERSHIP_AVERAGE_VIEW_RATE, 104
  field :VIDEO_VIEWERSHIP_AVERAGE_VIEW_TIME, 105
  field :VIDEO_VIEWERSHIP_CLICK_TO_PLAYS, 106
  field :VIDEO_VIEWERSHIP_COMPLETES, 107
  field :VIDEO_VIEWERSHIP_COMPLETION_RATE, 108
  field :VIDEO_VIEWERSHIP_ENGAGED_VIEWS, 109
  field :VIDEO_VIEWERSHIP_FIRST_QUARTILES, 110
  field :VIDEO_VIEWERSHIP_MIDPOINTS, 111
  field :VIDEO_VIEWERSHIP_SKIP_BUTTONS_SHOWN, 112
  field :VIDEO_VIEWERSHIP_STARTS, 113
  field :VIDEO_VIEWERSHIP_THIRD_QUARTILES, 114
  field :VIDEO_VIEWERSHIP_TOTAL_ERROR_COUNT, 115
  field :VIDEO_VIEWERSHIP_TOTAL_ERROR_RATE, 94
  field :VIDEO_VIEWERSHIP_VIDEO_LENGTH, 116
  field :VIDEO_VIEWERSHIP_VIEW_THROUGH_RATE, 117
  field :YIELD_GROUP_ESTIMATED_CPM, 88
  field :YIELD_GROUP_ESTIMATED_REVENUE, 87
  field :YIELD_GROUP_IMPRESSIONS, 85
  field :YIELD_GROUP_MEDIATION_FILL_RATE, 89
  field :YIELD_GROUP_MEDIATION_MATCHED_QUERIES, 86
  field :YIELD_GROUP_MEDIATION_PASSBACKS, 118
  field :YIELD_GROUP_MEDIATION_THIRD_PARTY_ECPM, 90
end

defmodule Google.Ads.Admanager.V1.Report.MetricValueType do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :PRIMARY, 0
  field :PRIMARY_PERCENT_OF_TOTAL, 1
  field :COMPARISON, 2
  field :COMPARISON_PERCENT_OF_TOTAL, 3
  field :ABSOLUTE_CHANGE, 4
  field :RELATIVE_CHANGE, 5
end

defmodule Google.Ads.Admanager.V1.Report.ReportType do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :REPORT_TYPE_UNSPECIFIED, 0
  field :HISTORICAL, 1
end

defmodule Google.Ads.Admanager.V1.Report.Visibility do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :HIDDEN, 0
  field :DRAFT, 1
  field :SAVED, 2
end

defmodule Google.Ads.Admanager.V1.Report.Filter.Operation do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :IN, 0
  field :NOT_IN, 1
  field :CONTAINS, 2
  field :NOT_CONTAINS, 3
  field :LESS_THAN, 4
  field :LESS_THAN_EQUALS, 5
  field :GREATER_THAN, 6
  field :GREATER_THAN_EQUALS, 7
  field :BETWEEN, 8
  field :MATCHES, 9
  field :NOT_MATCHES, 10
end

defmodule Google.Ads.Admanager.V1.Report.DateRange.RelativeDateRange do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :RELATIVE_DATE_RANGE_UNSPECIFIED, 0
  field :TODAY, 1
  field :YESTERDAY, 2
  field :THIS_WEEK, 3
  field :THIS_WEEK_TO_DATE, 29
  field :THIS_MONTH, 4
  field :THIS_MONTH_TO_DATE, 26
  field :THIS_QUARTER, 5
  field :THIS_QUARTER_TO_DATE, 27
  field :THIS_YEAR, 6
  field :THIS_YEAR_TO_DATE, 28
  field :LAST_WEEK, 7
  field :LAST_MONTH, 8
  field :LAST_QUARTER, 9
  field :LAST_YEAR, 10
  field :LAST_7_DAYS, 11
  field :LAST_30_DAYS, 12
  field :LAST_60_DAYS, 13
  field :LAST_90_DAYS, 14
  field :LAST_180_DAYS, 15
  field :LAST_360_DAYS, 16
  field :LAST_365_DAYS, 17
  field :LAST_3_MONTHS, 18
  field :LAST_6_MONTHS, 19
  field :LAST_12_MONTHS, 20
  field :ALL_AVAILABLE, 21
  field :PREVIOUS_PERIOD, 22
  field :SAME_PERIOD_PREVIOUS_YEAR, 24
end

defmodule Google.Ads.Admanager.V1.ScheduleOptions.DeliveryCondition do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :NEVER, 0
  field :ALWAYS, 1
  field :WHEN_FLAG_CONDITIONS_MET, 2
end

defmodule Google.Ads.Admanager.V1.Schedule.Frequency do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :FREQUENCY_UNSPECIFIED, 0
  field :HOURLY, 1
  field :TWO_TIMES_DAILY, 2
  field :THREE_TIMES_DAILY, 3
  field :FOUR_TIMES_DAILY, 4
  field :DAILY, 5
  field :WEEKLY, 6
  field :MONTHLY, 7
end

defmodule Google.Ads.Admanager.V1.Report.Value.IntList do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :values, 1, repeated: true, type: :int64
end

defmodule Google.Ads.Admanager.V1.Report.Value.StringList do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :values, 1, repeated: true, type: :string
end

defmodule Google.Ads.Admanager.V1.Report.Value do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  oneof :value, 0

  field :int_value, 1, type: :int64, json_name: "intValue", oneof: 0
  field :double_value, 2, type: :double, json_name: "doubleValue", oneof: 0
  field :string_value, 3, type: :string, json_name: "stringValue", oneof: 0
  field :bool_value, 4, type: :bool, json_name: "boolValue", oneof: 0

  field :int_list_value, 6,
    type: Google.Ads.Admanager.V1.Report.Value.IntList,
    json_name: "intListValue",
    oneof: 0

  field :string_list_value, 7,
    type: Google.Ads.Admanager.V1.Report.Value.StringList,
    json_name: "stringListValue",
    oneof: 0

  field :bytes_value, 8, type: :bytes, json_name: "bytesValue", oneof: 0
end

defmodule Google.Ads.Admanager.V1.Report.Sort do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :field, 1, type: Google.Ads.Admanager.V1.Report.Field, deprecated: false
  field :descending, 2, type: :bool, deprecated: false

  field :slice, 3,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.Report.Slice,
    deprecated: false

  field :time_period_index, 4,
    proto3_optional: true,
    type: :int32,
    json_name: "timePeriodIndex",
    deprecated: false

  field :metric_value_type, 5,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.Report.MetricValueType,
    json_name: "metricValueType",
    enum: true,
    deprecated: false
end

defmodule Google.Ads.Admanager.V1.Report.DataTable.Row do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :dimension_values, 1,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Value,
    json_name: "dimensionValues"

  field :metric_value_groups, 2,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.DataTable.MetricValueGroup,
    json_name: "metricValueGroups"
end

defmodule Google.Ads.Admanager.V1.Report.DataTable.MetricValueGroup do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :primary_values, 1,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Value,
    json_name: "primaryValues"

  field :primary_percent_of_total_values, 2,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Value,
    json_name: "primaryPercentOfTotalValues"

  field :comparison_values, 3,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Value,
    json_name: "comparisonValues"

  field :comparison_percent_of_total_values, 4,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Value,
    json_name: "comparisonPercentOfTotalValues"

  field :absolute_change_values, 5,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Value,
    json_name: "absoluteChangeValues"

  field :relative_change_values, 6,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Value,
    json_name: "relativeChangeValues"

  field :flag_values, 7, repeated: true, type: :bool, json_name: "flagValues"
end

defmodule Google.Ads.Admanager.V1.Report.DataTable do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3
end

defmodule Google.Ads.Admanager.V1.Report.Field do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  oneof :field, 0

  field :dimension, 1, type: Google.Ads.Admanager.V1.Report.Dimension, enum: true, oneof: 0
  field :metric, 2, type: Google.Ads.Admanager.V1.Report.Metric, enum: true, oneof: 0
end

defmodule Google.Ads.Admanager.V1.Report.Slice do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :dimension, 1,
    type: Google.Ads.Admanager.V1.Report.Dimension,
    enum: true,
    deprecated: false

  field :value, 2, type: Google.Ads.Admanager.V1.Report.Value, deprecated: false
end

defmodule Google.Ads.Admanager.V1.Report.Filter.FieldFilter do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :field, 1, type: Google.Ads.Admanager.V1.Report.Field, deprecated: false

  field :operation, 2,
    type: Google.Ads.Admanager.V1.Report.Filter.Operation,
    enum: true,
    deprecated: false

  field :values, 3, repeated: true, type: Google.Ads.Admanager.V1.Report.Value, deprecated: false

  field :slice, 4,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.Report.Slice,
    deprecated: false

  field :time_period_index, 5,
    proto3_optional: true,
    type: :int32,
    json_name: "timePeriodIndex",
    deprecated: false

  field :metric_value_type, 6,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.Report.MetricValueType,
    json_name: "metricValueType",
    enum: true,
    deprecated: false
end

defmodule Google.Ads.Admanager.V1.Report.Filter.FilterList do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :filters, 1,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Filter,
    deprecated: false
end

defmodule Google.Ads.Admanager.V1.Report.Filter do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  oneof :type, 0

  field :field_filter, 1,
    type: Google.Ads.Admanager.V1.Report.Filter.FieldFilter,
    json_name: "fieldFilter",
    oneof: 0

  field :not_filter, 2,
    type: Google.Ads.Admanager.V1.Report.Filter,
    json_name: "notFilter",
    oneof: 0

  field :and_filter, 3,
    type: Google.Ads.Admanager.V1.Report.Filter.FilterList,
    json_name: "andFilter",
    oneof: 0

  field :or_filter, 4,
    type: Google.Ads.Admanager.V1.Report.Filter.FilterList,
    json_name: "orFilter",
    oneof: 0
end

defmodule Google.Ads.Admanager.V1.Report.Flag do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :filters, 1,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Filter,
    deprecated: false

  field :name, 2, type: :string, deprecated: false
end

defmodule Google.Ads.Admanager.V1.Report.DateRange.FixedDateRange do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :start_date, 1, type: Google.Type.Date, json_name: "startDate", deprecated: false
  field :end_date, 2, type: Google.Type.Date, json_name: "endDate", deprecated: false
end

defmodule Google.Ads.Admanager.V1.Report.DateRange do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  oneof :date_range_type, 0

  field :fixed, 1, type: Google.Ads.Admanager.V1.Report.DateRange.FixedDateRange, oneof: 0

  field :relative, 2,
    type: Google.Ads.Admanager.V1.Report.DateRange.RelativeDateRange,
    enum: true,
    oneof: 0
end

defmodule Google.Ads.Admanager.V1.Report do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :name, 1, type: :string, deprecated: false
  field :report_id, 3, type: :int64, json_name: "reportId", deprecated: false

  field :visibility, 2,
    type: Google.Ads.Admanager.V1.Report.Visibility,
    enum: true,
    deprecated: false

  field :report_definition, 4,
    type: Google.Ads.Admanager.V1.ReportDefinition,
    json_name: "reportDefinition",
    deprecated: false

  field :display_name, 5, type: :string, json_name: "displayName", deprecated: false

  field :update_time, 6,
    type: Google.Protobuf.Timestamp,
    json_name: "updateTime",
    deprecated: false

  field :create_time, 7,
    type: Google.Protobuf.Timestamp,
    json_name: "createTime",
    deprecated: false

  field :locale, 8, type: :string, deprecated: false

  field :schedule_options, 9,
    type: Google.Ads.Admanager.V1.ScheduleOptions,
    json_name: "scheduleOptions",
    deprecated: false
end

defmodule Google.Ads.Admanager.V1.RunReportRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :name, 1, type: :string, deprecated: false
end

defmodule Google.Ads.Admanager.V1.RunReportMetadata do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :percent_complete, 2, type: :int32, json_name: "percentComplete"
  field :report, 4, type: :string, deprecated: false
end

defmodule Google.Ads.Admanager.V1.RunReportResponse do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :report_result, 1, type: :string, json_name: "reportResult"
end

defmodule Google.Ads.Admanager.V1.GetReportRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :name, 1, type: :string, deprecated: false
end

defmodule Google.Ads.Admanager.V1.ListReportsRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :parent, 1, type: :string, deprecated: false
  field :page_size, 2, type: :int32, json_name: "pageSize", deprecated: false
  field :page_token, 3, type: :string, json_name: "pageToken", deprecated: false
  field :filter, 4, type: :string, deprecated: false
  field :order_by, 5, type: :string, json_name: "orderBy", deprecated: false
  field :skip, 6, type: :int32, deprecated: false
end

defmodule Google.Ads.Admanager.V1.ListReportsResponse do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :reports, 1, repeated: true, type: Google.Ads.Admanager.V1.Report
  field :next_page_token, 2, type: :string, json_name: "nextPageToken"
  field :total_size, 3, type: :int32, json_name: "totalSize"
end

defmodule Google.Ads.Admanager.V1.CreateReportRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :parent, 1, type: :string, deprecated: false
  field :report, 2, type: Google.Ads.Admanager.V1.Report, deprecated: false
end

defmodule Google.Ads.Admanager.V1.UpdateReportRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :report, 1, type: Google.Ads.Admanager.V1.Report, deprecated: false

  field :update_mask, 2,
    type: Google.Protobuf.FieldMask,
    json_name: "updateMask",
    deprecated: false
end

defmodule Google.Ads.Admanager.V1.FetchReportResultRowsRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :name, 1, type: :string
  field :page_size, 2, type: :int32, json_name: "pageSize", deprecated: false
  field :page_token, 3, type: :string, json_name: "pageToken", deprecated: false
end

defmodule Google.Ads.Admanager.V1.FetchReportResultRowsResponse do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :rows, 1, repeated: true, type: Google.Ads.Admanager.V1.Report.DataTable.Row
  field :run_time, 2, type: Google.Protobuf.Timestamp, json_name: "runTime"

  field :date_ranges, 3,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.DateRange.FixedDateRange,
    json_name: "dateRanges"

  field :comparison_date_ranges, 4,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.DateRange.FixedDateRange,
    json_name: "comparisonDateRanges"

  field :total_row_count, 5, type: :int32, json_name: "totalRowCount"
  field :next_page_token, 6, type: :string, json_name: "nextPageToken"
end

defmodule Google.Ads.Admanager.V1.ReportDefinition do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :dimensions, 1,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Dimension,
    enum: true,
    deprecated: false

  field :metrics, 2,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Metric,
    enum: true,
    deprecated: false

  field :filters, 3,
    repeated: true,
    type: Google.Ads.Admanager.V1.Report.Filter,
    deprecated: false

  field :time_zone, 4, type: :string, json_name: "timeZone", deprecated: false
  field :currency_code, 5, type: :string, json_name: "currencyCode", deprecated: false

  field :date_range, 6,
    type: Google.Ads.Admanager.V1.Report.DateRange,
    json_name: "dateRange",
    deprecated: false

  field :comparison_date_range, 9,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.Report.DateRange,
    json_name: "comparisonDateRange",
    deprecated: false

  field :custom_dimension_key_ids, 7,
    repeated: true,
    type: :int64,
    json_name: "customDimensionKeyIds",
    deprecated: false

  field :line_item_custom_field_ids, 11,
    repeated: true,
    type: :int64,
    json_name: "lineItemCustomFieldIds",
    deprecated: false

  field :order_custom_field_ids, 12,
    repeated: true,
    type: :int64,
    json_name: "orderCustomFieldIds",
    deprecated: false

  field :creative_custom_field_ids, 13,
    repeated: true,
    type: :int64,
    json_name: "creativeCustomFieldIds",
    deprecated: false

  field :report_type, 8,
    type: Google.Ads.Admanager.V1.Report.ReportType,
    json_name: "reportType",
    enum: true,
    deprecated: false

  field :time_period_column, 10,
    type: Google.Ads.Admanager.V1.Report.TimePeriodColumn,
    json_name: "timePeriodColumn",
    enum: true,
    deprecated: false

  field :flags, 14, repeated: true, type: Google.Ads.Admanager.V1.Report.Flag, deprecated: false
  field :sorts, 15, repeated: true, type: Google.Ads.Admanager.V1.Report.Sort, deprecated: false
end

defmodule Google.Ads.Admanager.V1.ScheduleOptions do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :schedule, 1, type: Google.Ads.Admanager.V1.Schedule

  field :delivery_condition, 2,
    type: Google.Ads.Admanager.V1.ScheduleOptions.DeliveryCondition,
    json_name: "deliveryCondition",
    enum: true

  field :flags, 3, repeated: true, type: Google.Ads.Admanager.V1.Report.Flag, deprecated: false
end

defmodule Google.Ads.Admanager.V1.Schedule.WeeklySchedule do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :weekly_scheduled_days, 1,
    repeated: true,
    type: Google.Type.DayOfWeek,
    json_name: "weeklyScheduledDays",
    enum: true
end

defmodule Google.Ads.Admanager.V1.Schedule.MonthlySchedule do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  field :monthly_scheduled_days, 1,
    repeated: true,
    type: :int32,
    json_name: "monthlyScheduledDays"
end

defmodule Google.Ads.Admanager.V1.Schedule do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.0", syntax: :proto3

  oneof :frequency_schedule, 0

  field :weekly_schedule, 6,
    type: Google.Ads.Admanager.V1.Schedule.WeeklySchedule,
    json_name: "weeklySchedule",
    oneof: 0

  field :monthly_schedule, 7,
    type: Google.Ads.Admanager.V1.Schedule.MonthlySchedule,
    json_name: "monthlySchedule",
    oneof: 0

  field :start_date, 1, type: Google.Type.Date, json_name: "startDate"
  field :end_date, 2, type: Google.Type.Date, json_name: "endDate"
  field :frequency, 3, type: Google.Ads.Admanager.V1.Schedule.Frequency, enum: true
  field :start_time, 4, type: Google.Type.TimeOfDay, json_name: "startTime"
end

defmodule Google.Ads.Admanager.V1.ReportService.Service do
  @moduledoc false

  use GRPC.Service,
    name: "google.ads.admanager.v1.ReportService",
    protoc_gen_elixir_version: "0.14.0"

  rpc :GetReport, Google.Ads.Admanager.V1.GetReportRequest, Google.Ads.Admanager.V1.Report

  rpc :ListReports,
      Google.Ads.Admanager.V1.ListReportsRequest,
      Google.Ads.Admanager.V1.ListReportsResponse

  rpc :CreateReport, Google.Ads.Admanager.V1.CreateReportRequest, Google.Ads.Admanager.V1.Report

  rpc :UpdateReport, Google.Ads.Admanager.V1.UpdateReportRequest, Google.Ads.Admanager.V1.Report

  rpc :RunReport, Google.Ads.Admanager.V1.RunReportRequest, Google.Longrunning.Operation

  rpc :FetchReportResultRows,
      Google.Ads.Admanager.V1.FetchReportResultRowsRequest,
      Google.Ads.Admanager.V1.FetchReportResultRowsResponse
end

defmodule Google.Ads.Admanager.V1.ReportService.Stub do
  @moduledoc false

  use GRPC.Stub, service: Google.Ads.Admanager.V1.ReportService.Service
end
