defmodule Google.Ads.Admanager.V1.ReportDefinition.ReportType do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :REPORT_TYPE_UNSPECIFIED, 0
  field :HISTORICAL, 1
  field :REACH, 5
  field :PRIVACY_AND_MESSAGING, 6
  field :AD_SPEED, 13
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Dimension do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :DIMENSION_UNSPECIFIED, 0
  field :ACTIVE_VIEW_MEASUREMENT_SOURCE, 575
  field :ACTIVE_VIEW_MEASUREMENT_SOURCE_NAME, 576
  field :ADVERTISER_CREDIT_STATUS, 475
  field :ADVERTISER_CREDIT_STATUS_NAME, 476
  field :ADVERTISER_DOMAIN_NAME, 242
  field :ADVERTISER_EXTERNAL_ID, 228
  field :ADVERTISER_ID, 131
  field :ADVERTISER_LABELS, 230
  field :ADVERTISER_LABEL_IDS, 229
  field :ADVERTISER_NAME, 132
  field :ADVERTISER_PRIMARY_CONTACT, 227
  field :ADVERTISER_STATUS, 471
  field :ADVERTISER_STATUS_NAME, 472
  field :ADVERTISER_TYPE, 473
  field :ADVERTISER_TYPE_NAME, 474
  field :ADVERTISER_VERTICAL, 580
  field :ADX_PRODUCT, 499
  field :ADX_PRODUCT_NAME, 500
  field :AD_EXPERIENCES_TYPE, 641
  field :AD_EXPERIENCES_TYPE_NAME, 642
  field :AD_LOCATION, 390
  field :AD_LOCATION_NAME, 391
  field :AD_TECHNOLOGY_PROVIDER_DOMAIN, 620
  field :AD_TECHNOLOGY_PROVIDER_ID, 621
  field :AD_TECHNOLOGY_PROVIDER_NAME, 622
  field :AD_TYPE, 497
  field :AD_TYPE_NAME, 498
  field :AD_UNIT_CODE, 64
  field :AD_UNIT_CODE_LEVEL_1, 65
  field :AD_UNIT_CODE_LEVEL_10, 74
  field :AD_UNIT_CODE_LEVEL_11, 75
  field :AD_UNIT_CODE_LEVEL_12, 76
  field :AD_UNIT_CODE_LEVEL_13, 77
  field :AD_UNIT_CODE_LEVEL_14, 78
  field :AD_UNIT_CODE_LEVEL_15, 79
  field :AD_UNIT_CODE_LEVEL_16, 80
  field :AD_UNIT_CODE_LEVEL_2, 66
  field :AD_UNIT_CODE_LEVEL_3, 67
  field :AD_UNIT_CODE_LEVEL_4, 68
  field :AD_UNIT_CODE_LEVEL_5, 69
  field :AD_UNIT_CODE_LEVEL_6, 70
  field :AD_UNIT_CODE_LEVEL_7, 71
  field :AD_UNIT_CODE_LEVEL_8, 72
  field :AD_UNIT_CODE_LEVEL_9, 73
  field :AD_UNIT_ID, 25
  field :AD_UNIT_ID_ALL_LEVEL, 27
  field :AD_UNIT_ID_LEVEL_1, 30
  field :AD_UNIT_ID_LEVEL_10, 48
  field :AD_UNIT_ID_LEVEL_11, 50
  field :AD_UNIT_ID_LEVEL_12, 52
  field :AD_UNIT_ID_LEVEL_13, 54
  field :AD_UNIT_ID_LEVEL_14, 56
  field :AD_UNIT_ID_LEVEL_15, 58
  field :AD_UNIT_ID_LEVEL_16, 60
  field :AD_UNIT_ID_LEVEL_2, 32
  field :AD_UNIT_ID_LEVEL_3, 34
  field :AD_UNIT_ID_LEVEL_4, 36
  field :AD_UNIT_ID_LEVEL_5, 38
  field :AD_UNIT_ID_LEVEL_6, 40
  field :AD_UNIT_ID_LEVEL_7, 42
  field :AD_UNIT_ID_LEVEL_8, 44
  field :AD_UNIT_ID_LEVEL_9, 46
  field :AD_UNIT_ID_TOP_LEVEL, 142
  field :AD_UNIT_NAME, 26
  field :AD_UNIT_NAME_ALL_LEVEL, 29
  field :AD_UNIT_NAME_LEVEL_1, 31
  field :AD_UNIT_NAME_LEVEL_10, 49
  field :AD_UNIT_NAME_LEVEL_11, 51
  field :AD_UNIT_NAME_LEVEL_12, 53
  field :AD_UNIT_NAME_LEVEL_13, 55
  field :AD_UNIT_NAME_LEVEL_14, 57
  field :AD_UNIT_NAME_LEVEL_15, 59
  field :AD_UNIT_NAME_LEVEL_16, 61
  field :AD_UNIT_NAME_LEVEL_2, 33
  field :AD_UNIT_NAME_LEVEL_3, 35
  field :AD_UNIT_NAME_LEVEL_4, 37
  field :AD_UNIT_NAME_LEVEL_5, 39
  field :AD_UNIT_NAME_LEVEL_6, 41
  field :AD_UNIT_NAME_LEVEL_7, 43
  field :AD_UNIT_NAME_LEVEL_8, 45
  field :AD_UNIT_NAME_LEVEL_9, 47
  field :AD_UNIT_NAME_TOP_LEVEL, 143
  field :AD_UNIT_REWARD_AMOUNT, 63
  field :AD_UNIT_REWARD_TYPE, 62
  field :AD_UNIT_STATUS, 206
  field :AD_UNIT_STATUS_NAME, 207
  field :AGENCY_LEVEL_1_ID, 565
  field :AGENCY_LEVEL_1_NAME, 566
  field :AGENCY_LEVEL_2_ID, 567
  field :AGENCY_LEVEL_2_NAME, 568
  field :AGENCY_LEVEL_3_ID, 569
  field :AGENCY_LEVEL_3_NAME, 570
  field :AGE_BRACKET, 508
  field :AGE_BRACKET_NAME, 582
  field :APP_TRACKING_TRANSPARENCY_CONSENT_STATUS, 442
  field :APP_TRACKING_TRANSPARENCY_CONSENT_STATUS_NAME, 443
  field :APP_VERSION, 392
  field :AUCTION_PACKAGE_DEAL, 579
  field :AUCTION_PACKAGE_DEAL_ID, 571
  field :AUDIENCE_SEGMENT_ID_TARGETED, 584
  field :AUDIENCE_SEGMENT_TARGETED, 585
  field :AUTO_REFRESHED_TRAFFIC, 421
  field :AUTO_REFRESHED_TRAFFIC_NAME, 422
  field :BIDDER_ENCRYPTED_ID, 493
  field :BIDDER_NAME, 494
  field :BID_RANGE, 679
  field :BID_REJECTION_REASON, 599
  field :BID_REJECTION_REASON_NAME, 600
  field :BRANDING_TYPE, 383
  field :BRANDING_TYPE_NAME, 384
  field :BROWSER_CATEGORY, 119
  field :BROWSER_CATEGORY_NAME, 120
  field :BROWSER_ID, 235
  field :BROWSER_NAME, 236
  field :BUYER_NETWORK_ID, 448
  field :BUYER_NETWORK_NAME, 449
  field :CALLOUT_STATUS_CATEGORY, 588
  field :CALLOUT_STATUS_CATEGORY_NAME, 589
  field :CARRIER_ID, 369
  field :CARRIER_NAME, 368
  field :CHANNEL, 501
  field :CHILD_NETWORK_CODE, 542
  field :CHILD_NETWORK_ID, 544
  field :CHILD_PARTNER_NAME, 543
  field :CITY_ID, 459
  field :CITY_NAME, 452
  field :CLASSIFIED_ADVERTISER_ID, 133
  field :CLASSIFIED_ADVERTISER_NAME, 134
  field :CLASSIFIED_BRAND_ID, 243
  field :CLASSIFIED_BRAND_NAME, 244
  field :CONTENT_CMS_NAME, 643
  field :CONTENT_CMS_VIDEO_ID, 644
  field :CONTENT_ID, 246
  field :CONTENT_MAPPING_PRESENCE, 731
  field :CONTENT_MAPPING_PRESENCE_NAME, 732
  field :CONTENT_NAME, 247
  field :CONTINENT, 469
  field :CONTINENT_NAME, 470
  field :COUNTRY_CODE, 466
  field :COUNTRY_ID, 11
  field :COUNTRY_NAME, 12
  field :CREATIVE_BILLING_TYPE, 366
  field :CREATIVE_BILLING_TYPE_NAME, 367
  field :CREATIVE_CLICK_THROUGH_URL, 174
  field :CREATIVE_ID, 138
  field :CREATIVE_NAME, 139
  field :CREATIVE_POLICIES_FILTERING, 711
  field :CREATIVE_POLICIES_FILTERING_NAME, 712
  field :CREATIVE_PROTECTIONS_FILTERING, 704
  field :CREATIVE_PROTECTIONS_FILTERING_NAME, 705
  field :CREATIVE_SET_ROLE_TYPE, 686
  field :CREATIVE_SET_ROLE_TYPE_NAME, 687
  field :CREATIVE_TECHNOLOGY, 148
  field :CREATIVE_TECHNOLOGY_NAME, 149
  field :CREATIVE_THIRD_PARTY_VENDOR, 361
  field :CREATIVE_TYPE, 344
  field :CREATIVE_TYPE_NAME, 345
  field :CREATIVE_VENDOR_ID, 706
  field :CREATIVE_VENDOR_NAME, 707
  field :CREATIVE_VIDEO_REDIRECT_THIRD_PARTY, 562
  field :CURATOR_ID, 572
  field :CURATOR_NAME, 573
  field :CUSTOM_EVENT_ID, 737
  field :CUSTOM_EVENT_NAME, 735
  field :CUSTOM_EVENT_TYPE, 736
  field :CUSTOM_EVENT_TYPE_NAME, 738
  field :CUSTOM_SPOT_ID, 423
  field :CUSTOM_SPOT_NAME, 424
  field :DATE, 3
  field :DAY_OF_WEEK, 4
  field :DEAL_BUYER_ID, 240
  field :DEAL_BUYER_NAME, 241
  field :DEAL_ID, 436
  field :DEAL_NAME, 437
  field :DELIVERED_SECURE_SIGNAL_ID, 309
  field :DELIVERED_SECURE_SIGNAL_NAME, 310
  field :DEMAND_CHANNEL, 9
  field :DEMAND_CHANNEL_NAME, 10
  field :DEMAND_SOURCE, 592
  field :DEMAND_SOURCE_NAME, 593
  field :DEMAND_SUBCHANNEL, 22
  field :DEMAND_SUBCHANNEL_NAME, 23
  field :DEVICE, 226
  field :DEVICE_CATEGORY, 15
  field :DEVICE_CATEGORY_NAME, 16
  field :DEVICE_MANUFACTURER_ID, 525
  field :DEVICE_MANUFACTURER_NAME, 526
  field :DEVICE_MODEL_ID, 527
  field :DEVICE_MODEL_NAME, 528
  field :DEVICE_NAME, 225
  field :DSP_SEAT_ID, 564
  field :DYNAMIC_ALLOCATION_TYPE, 502
  field :DYNAMIC_ALLOCATION_TYPE_NAME, 503
  field :ESP_DELIVERY, 623
  field :ESP_DELIVERY_NAME, 624
  field :ESP_PRESENCE, 625
  field :ESP_PRESENCE_NAME, 626
  field :EXCHANGE_BIDDING_DEAL_ID, 715
  field :EXCHANGE_BIDDING_DEAL_TYPE, 714
  field :EXCHANGE_BIDDING_DEAL_TYPE_NAME, 723
  field :EXCHANGE_THIRD_PARTY_COMPANY_ID, 185
  field :EXCHANGE_THIRD_PARTY_COMPANY_NAME, 186
  field :FIRST_LOOK_PRICING_RULE_ID, 248
  field :FIRST_LOOK_PRICING_RULE_NAME, 249
  field :FIRST_PARTY_ID_STATUS, 404
  field :FIRST_PARTY_ID_STATUS_NAME, 405
  field :GENDER, 509
  field :GENDER_NAME, 583
  field :GOOGLE_ANALYTICS_STREAM_ID, 519
  field :GOOGLE_ANALYTICS_STREAM_NAME, 520
  field :HBT_YIELD_PARTNER_ID, 659
  field :HBT_YIELD_PARTNER_NAME, 660
  field :HEADER_BIDDER_INTEGRATION_TYPE, 718
  field :HEADER_BIDDER_INTEGRATION_TYPE_NAME, 719
  field :HOUR, 100
  field :IMPRESSION_COUNTING_METHOD, 577
  field :IMPRESSION_COUNTING_METHOD_NAME, 578
  field :INTERACTION_TYPE, 223
  field :INTERACTION_TYPE_NAME, 224
  field :INTEREST, 510
  field :INVENTORY_FORMAT, 17
  field :INVENTORY_FORMAT_NAME, 18
  field :INVENTORY_SHARE_ASSIGNMENT_ID, 648
  field :INVENTORY_SHARE_ASSIGNMENT_NAME, 649
  field :INVENTORY_SHARE_OUTCOME, 603
  field :INVENTORY_SHARE_OUTCOME_NAME, 604
  field :INVENTORY_SHARE_PARTNER_AD_SERVER, 652
  field :INVENTORY_SHARE_PARTNER_AD_SERVER_NAME, 653
  field :INVENTORY_SHARE_TARGET_SHARE_PERCENT, 654
  field :INVENTORY_SHARE_TYPE, 650
  field :INVENTORY_SHARE_TYPE_NAME, 651
  field :INVENTORY_TYPE, 19
  field :INVENTORY_TYPE_NAME, 20
  field :IS_ADX_DIRECT, 382
  field :IS_CURATION_TARGETED, 574
  field :IS_DROPPED, 464
  field :IS_FIRST_LOOK_DEAL, 401
  field :KEY_VALUES_ID, 214
  field :KEY_VALUES_NAME, 215
  field :LINE_ITEM_AGENCY, 663
  field :LINE_ITEM_ARCHIVED, 188
  field :LINE_ITEM_COMPANION_DELIVERY_OPTION, 204
  field :LINE_ITEM_COMPANION_DELIVERY_OPTION_NAME, 205
  field :LINE_ITEM_COMPUTED_STATUS, 250
  field :LINE_ITEM_COMPUTED_STATUS_NAME, 251
  field :LINE_ITEM_CONTRACTED_QUANTITY, 92
  field :LINE_ITEM_COST_PER_UNIT, 85
  field :LINE_ITEM_COST_TYPE, 212
  field :LINE_ITEM_COST_TYPE_NAME, 213
  field :LINE_ITEM_CREATIVE_END_DATE, 176
  field :LINE_ITEM_CREATIVE_ROTATION_TYPE, 189
  field :LINE_ITEM_CREATIVE_ROTATION_TYPE_NAME, 190
  field :LINE_ITEM_CREATIVE_START_DATE, 175
  field :LINE_ITEM_CURRENCY_CODE, 180
  field :LINE_ITEM_DELIVERY_INDICATOR, 87
  field :LINE_ITEM_DELIVERY_RATE_TYPE, 191
  field :LINE_ITEM_DELIVERY_RATE_TYPE_NAME, 192
  field :LINE_ITEM_DISCOUNT_ABSOLUTE, 195
  field :LINE_ITEM_DISCOUNT_PERCENTAGE, 196
  field :LINE_ITEM_END_DATE, 81
  field :LINE_ITEM_END_DATE_TIME, 83
  field :LINE_ITEM_ENVIRONMENT_TYPE, 201
  field :LINE_ITEM_ENVIRONMENT_TYPE_NAME, 202
  field :LINE_ITEM_EXTERNAL_DEAL_ID, 97
  field :LINE_ITEM_EXTERNAL_ID, 86
  field :LINE_ITEM_FREQUENCY_CAP, 256
  field :LINE_ITEM_ID, 1
  field :LINE_ITEM_LABELS, 667
  field :LINE_ITEM_LABEL_IDS, 665
  field :LINE_ITEM_LAST_MODIFIED_BY_APP, 181
  field :LINE_ITEM_LIFETIME_CLICKS, 95
  field :LINE_ITEM_LIFETIME_IMPRESSIONS, 94
  field :LINE_ITEM_LIFETIME_VIEWABLE_IMPRESSIONS, 96
  field :LINE_ITEM_MAKEGOOD, 89
  field :LINE_ITEM_NAME, 2
  field :LINE_ITEM_NON_CPD_BOOKED_REVENUE, 98
  field :LINE_ITEM_OPTIMIZABLE, 90
  field :LINE_ITEM_PO_NUMBER, 669
  field :LINE_ITEM_PRIMARY_GOAL_TYPE, 210
  field :LINE_ITEM_PRIMARY_GOAL_TYPE_NAME, 211
  field :LINE_ITEM_PRIMARY_GOAL_UNITS_ABSOLUTE, 93
  field :LINE_ITEM_PRIMARY_GOAL_UNITS_PERCENTAGE, 396
  field :LINE_ITEM_PRIMARY_GOAL_UNIT_TYPE, 208
  field :LINE_ITEM_PRIMARY_GOAL_UNIT_TYPE_NAME, 209
  field :LINE_ITEM_PRIORITY, 24
  field :LINE_ITEM_RESERVATION_STATUS, 304
  field :LINE_ITEM_RESERVATION_STATUS_NAME, 305
  field :LINE_ITEM_SALESPERSON, 671
  field :LINE_ITEM_SECONDARY_SALESPEOPLE, 673
  field :LINE_ITEM_SECONDARY_TRAFFICKERS, 675
  field :LINE_ITEM_START_DATE, 82
  field :LINE_ITEM_START_DATE_TIME, 84
  field :LINE_ITEM_TRAFFICKER, 677
  field :LINE_ITEM_TYPE, 193
  field :LINE_ITEM_TYPE_NAME, 194
  field :LINE_ITEM_UNLIMITED_END, 187
  field :LINE_ITEM_VALUE_COST_PER_UNIT, 88
  field :LINE_ITEM_WEB_PROPERTY_CODE, 179
  field :MASTER_COMPANION_CREATIVE_ID, 140
  field :MASTER_COMPANION_CREATIVE_NAME, 141
  field :MEDIATION_TYPE, 701
  field :MEDIATION_TYPE_NAME, 754
  field :MEDIATION_YIELD_PARTNER_ID, 661
  field :MEDIATION_YIELD_PARTNER_NAME, 662
  field :METRO_ID, 453
  field :METRO_NAME, 454
  field :MOBILE_APP_FREE, 128
  field :MOBILE_APP_ICON_URL, 129
  field :MOBILE_APP_ID, 123
  field :MOBILE_APP_NAME, 127
  field :MOBILE_APP_OWNERSHIP_STATUS, 311
  field :MOBILE_APP_OWNERSHIP_STATUS_NAME, 312
  field :MOBILE_APP_STORE, 125
  field :MOBILE_APP_STORE_NAME, 245
  field :MOBILE_INVENTORY_TYPE, 99
  field :MOBILE_INVENTORY_TYPE_NAME, 21
  field :MOBILE_RENDERING_SDK, 646
  field :MOBILE_RENDERING_SDK_NAME, 647
  field :MOBILE_SDK_MAJOR_VERSION, 692
  field :MOBILE_SDK_MINOR_VERSION, 693
  field :MOBILE_SDK_VERSION_NAME, 130
  field :MONTH_YEAR, 6
  field :NATIVE_AD_FORMAT_ID, 255
  field :NATIVE_AD_FORMAT_NAME, 254
  field :NATIVE_STYLE_ID, 253
  field :NATIVE_STYLE_NAME, 252
  field :NO_FILL_REASON_CATEGORY, 586
  field :NO_FILL_REASON_CATEGORY_NAME, 587
  field :OPERATING_SYSTEM_CATEGORY, 117
  field :OPERATING_SYSTEM_CATEGORY_NAME, 118
  field :OPERATING_SYSTEM_VERSION_ID, 238
  field :OPERATING_SYSTEM_VERSION_NAME, 237
  field :OPTIMIZATION_TYPE, 639
  field :OPTIMIZATION_TYPE_NAME, 640
  field :ORDER_AGENCY, 150
  field :ORDER_AGENCY_ID, 151
  field :ORDER_BOOKED_CPC, 152
  field :ORDER_BOOKED_CPM, 153
  field :ORDER_DELIVERY_STATUS, 231
  field :ORDER_DELIVERY_STATUS_NAME, 239
  field :ORDER_END_DATE, 154
  field :ORDER_END_DATE_TIME, 155
  field :ORDER_EXTERNAL_ID, 156
  field :ORDER_ID, 7
  field :ORDER_LABELS, 170
  field :ORDER_LABEL_IDS, 171
  field :ORDER_LIFETIME_CLICKS, 158
  field :ORDER_LIFETIME_IMPRESSIONS, 159
  field :ORDER_NAME, 8
  field :ORDER_PO_NUMBER, 160
  field :ORDER_PROGRAMMATIC, 157
  field :ORDER_SALESPERSON, 161
  field :ORDER_SALESPERSON_ID, 629
  field :ORDER_SECONDARY_SALESPEOPLE, 164
  field :ORDER_SECONDARY_SALESPEOPLE_ID, 165
  field :ORDER_SECONDARY_TRAFFICKERS, 166
  field :ORDER_SECONDARY_TRAFFICKERS_ID, 167
  field :ORDER_START_DATE, 168
  field :ORDER_START_DATE_TIME, 169
  field :ORDER_TRAFFICKER, 162
  field :ORDER_TRAFFICKER_ID, 163
  field :ORDER_UNLIMITED_END, 203
  field :PAGE_PATH, 511
  field :PAGE_TITLE_AND_SCREEN_CLASS, 512
  field :PAGE_TITLE_AND_SCREEN_NAME, 513
  field :PLACEMENT_ID, 113
  field :PLACEMENT_ID_ALL, 144
  field :PLACEMENT_NAME, 114
  field :PLACEMENT_NAME_ALL, 145
  field :PLACEMENT_STATUS, 362
  field :PLACEMENT_STATUS_NAME, 364
  field :PLACEMENT_STATUS_NAME_ALL, 365
  field :POSTAL_CODE_ID, 455
  field :POSTAL_CODE_NAME, 456
  field :PPID_STATUS, 406
  field :PPID_STATUS_NAME, 407
  field :PREDICTED_VIEWABILITY_BUCKET, 633
  field :PREDICTED_VIEWABILITY_BUCKET_NAME, 634
  field :PRESENTED_SECURE_SIGNAL_ID, 495
  field :PRESENTED_SECURE_SIGNAL_NAME, 496
  field :PRIMARY_PERSONALIZATION_ID_TYPE, 408
  field :PRIMARY_PERSONALIZATION_ID_TYPE_NAME, 409
  field :PROGRAMMATIC_BUYER_ID, 240
  field :PROGRAMMATIC_BUYER_NAME, 241
  field :PROGRAMMATIC_CHANNEL, 13
  field :PROGRAMMATIC_CHANNEL_NAME, 14
  field :PUBLISHER_PROVIDED_SIGNALS_ALL_LEVELS_EXTERNAL_CODE, 410
  field :PUBLISHER_PROVIDED_SIGNALS_ALL_LEVELS_IDS, 546
  field :PUBLISHER_PROVIDED_SIGNALS_ALL_LEVELS_NAME, 412
  field :PUBLISHER_PROVIDED_SIGNALS_ALL_LEVELS_TIER, 413
  field :PUBLISHER_PROVIDED_SIGNALS_ALL_LEVELS_TYPE, 414
  field :PUBLISHER_PROVIDED_SIGNALS_DELIVERED_EXTERNAL_CODE, 425
  field :PUBLISHER_PROVIDED_SIGNALS_DELIVERED_IDS, 545
  field :PUBLISHER_PROVIDED_SIGNALS_DELIVERED_NAME, 427
  field :PUBLISHER_PROVIDED_SIGNALS_DELIVERED_TIER, 428
  field :PUBLISHER_PROVIDED_SIGNALS_DELIVERED_TYPE, 429
  field :PUBLISHER_PROVIDED_SIGNALS_TOP_LEVEL_EXTERNAL_CODE, 415
  field :PUBLISHER_PROVIDED_SIGNALS_TOP_LEVEL_ID, 416
  field :PUBLISHER_PROVIDED_SIGNALS_TOP_LEVEL_NAME, 417
  field :PUBLISHER_PROVIDED_SIGNALS_TOP_LEVEL_TIER, 418
  field :PUBLISHER_PROVIDED_SIGNALS_TOP_LEVEL_TYPE, 419
  field :PUBLISHER_PROVIDED_SIGNAL_DATA_PROVIDER_ID, 136
  field :PUBLISHER_PROVIDED_SIGNAL_DATA_PROVIDER_NAME, 137
  field :REGION_ID, 457
  field :REGION_NAME, 458
  field :REJECTION_CLASS_CATEGORY, 590
  field :REJECTION_CLASS_CATEGORY_NAME, 591
  field :RENDERED_CREATIVE_SIZE, 343
  field :REQUESTED_AD_SIZES, 352
  field :REQUEST_TYPE, 146
  field :REQUEST_TYPE_NAME, 147
  field :SERVER_SIDE_UNWRAPPING_ELIGIBLE, 597
  field :SERVING_RESTRICTION, 631
  field :SERVING_RESTRICTION_NAME, 632
  field :SITE, 387
  field :TARGETING_ID, 232
  field :TARGETING_NAME, 233
  field :TARGETING_TYPE, 385
  field :TARGETING_TYPE_NAME, 386
  field :THIRD_PARTY_ID_STATUS, 402
  field :THIRD_PARTY_ID_STATUS_NAME, 403
  field :TOPICS_STATUS, 504
  field :TOPICS_STATUS_NAME, 505
  field :TOP_PRIVATE_DOMAIN, 444
  field :TRAFFIC_SOURCE, 388
  field :TRAFFIC_SOURCE_NAME, 389
  field :UNIFIED_PRICING_RULE_ID, 393
  field :UNIFIED_PRICING_RULE_NAME, 394
  field :URL, 506
  field :URL_ID, 507
  field :USER_MESSAGES_ENTITLEMENT_SOURCE, 635
  field :USER_MESSAGES_ENTITLEMENT_SOURCE_NAME, 636
  field :USER_MESSAGES_OPERATING_SYSTEM_CRITERIA_ID, 637
  field :USER_MESSAGES_OPERATING_SYSTEM_CRITERIA_NAME, 638
  field :VAST_VERSION, 554
  field :VAST_VERSION_NAME, 555
  field :VIDEO_AD_BREAK_TYPE, 556
  field :VIDEO_AD_BREAK_TYPE_NAME, 557
  field :VIDEO_AD_DURATION, 450
  field :VIDEO_AD_FORMATS_RULE, 561
  field :VIDEO_AD_FORMATS_RULE_ID, 560
  field :VIDEO_AD_REQUEST_DURATION, 558
  field :VIDEO_AD_REQUEST_DURATION_MIDPOINT_NAME, 751
  field :VIDEO_AD_REQUEST_DURATION_NAME, 559
  field :VIDEO_AD_REQUEST_SOURCE, 438
  field :VIDEO_AD_REQUEST_SOURCE_NAME, 439
  field :VIDEO_AD_TYPE, 432
  field :VIDEO_AD_TYPE_NAME, 433
  field :VIDEO_CONTINUOUS_PLAY_TYPE, 721
  field :VIDEO_CONTINUOUS_PLAY_TYPE_NAME, 722
  field :VIDEO_FALLBACK_POSITION, 530
  field :VIDEO_MEASUREMENT_SOURCE, 601
  field :VIDEO_MEASUREMENT_SOURCE_NAME, 602
  field :VIDEO_PLCMT, 172
  field :VIDEO_PLCMT_NAME, 173
  field :VIDEO_POSITION_IN_POD, 538
  field :VIDEO_POSITION_OF_POD, 539
  field :VIDEO_SDK_VERSION, 440
  field :VIDEO_SDK_VERSION_NAME, 441
  field :VIDEO_STITCHER_TYPE, 752
  field :VIDEO_STITCHER_TYPE_NAME, 753
  field :WEEK, 5
  field :YIELD_GROUP_BUYER_NAME, 184
  field :YIELD_GROUP_BUYER_TAG_NAME, 627
  field :YIELD_GROUP_ID, 182
  field :YIELD_GROUP_NAME, 183
  field :YOUTUBE_AD_DURATION_BUCKET, 430
  field :YOUTUBE_AD_DURATION_BUCKET_NAME, 431
  field :YOUTUBE_AD_TYPE, 399
  field :YOUTUBE_AD_TYPE_NAME, 400
  field :LINE_ITEM_CUSTOM_FIELD_0_OPTION_ID, 10000
  field :LINE_ITEM_CUSTOM_FIELD_1_OPTION_ID, 10001
  field :LINE_ITEM_CUSTOM_FIELD_2_OPTION_ID, 10002
  field :LINE_ITEM_CUSTOM_FIELD_3_OPTION_ID, 10003
  field :LINE_ITEM_CUSTOM_FIELD_4_OPTION_ID, 10004
  field :LINE_ITEM_CUSTOM_FIELD_5_OPTION_ID, 10005
  field :LINE_ITEM_CUSTOM_FIELD_6_OPTION_ID, 10006
  field :LINE_ITEM_CUSTOM_FIELD_7_OPTION_ID, 10007
  field :LINE_ITEM_CUSTOM_FIELD_8_OPTION_ID, 10008
  field :LINE_ITEM_CUSTOM_FIELD_9_OPTION_ID, 10009
  field :LINE_ITEM_CUSTOM_FIELD_10_OPTION_ID, 10010
  field :LINE_ITEM_CUSTOM_FIELD_11_OPTION_ID, 10011
  field :LINE_ITEM_CUSTOM_FIELD_12_OPTION_ID, 10012
  field :LINE_ITEM_CUSTOM_FIELD_13_OPTION_ID, 10013
  field :LINE_ITEM_CUSTOM_FIELD_14_OPTION_ID, 10014
  field :LINE_ITEM_CUSTOM_FIELD_0_VALUE, 11000
  field :LINE_ITEM_CUSTOM_FIELD_1_VALUE, 11001
  field :LINE_ITEM_CUSTOM_FIELD_2_VALUE, 11002
  field :LINE_ITEM_CUSTOM_FIELD_3_VALUE, 11003
  field :LINE_ITEM_CUSTOM_FIELD_4_VALUE, 11004
  field :LINE_ITEM_CUSTOM_FIELD_5_VALUE, 11005
  field :LINE_ITEM_CUSTOM_FIELD_6_VALUE, 11006
  field :LINE_ITEM_CUSTOM_FIELD_7_VALUE, 11007
  field :LINE_ITEM_CUSTOM_FIELD_8_VALUE, 11008
  field :LINE_ITEM_CUSTOM_FIELD_9_VALUE, 11009
  field :LINE_ITEM_CUSTOM_FIELD_10_VALUE, 11010
  field :LINE_ITEM_CUSTOM_FIELD_11_VALUE, 11011
  field :LINE_ITEM_CUSTOM_FIELD_12_VALUE, 11012
  field :LINE_ITEM_CUSTOM_FIELD_13_VALUE, 11013
  field :LINE_ITEM_CUSTOM_FIELD_14_VALUE, 11014
  field :ORDER_CUSTOM_FIELD_0_OPTION_ID, 12000
  field :ORDER_CUSTOM_FIELD_1_OPTION_ID, 12001
  field :ORDER_CUSTOM_FIELD_2_OPTION_ID, 12002
  field :ORDER_CUSTOM_FIELD_3_OPTION_ID, 12003
  field :ORDER_CUSTOM_FIELD_4_OPTION_ID, 12004
  field :ORDER_CUSTOM_FIELD_5_OPTION_ID, 12005
  field :ORDER_CUSTOM_FIELD_6_OPTION_ID, 12006
  field :ORDER_CUSTOM_FIELD_7_OPTION_ID, 12007
  field :ORDER_CUSTOM_FIELD_8_OPTION_ID, 12008
  field :ORDER_CUSTOM_FIELD_9_OPTION_ID, 12009
  field :ORDER_CUSTOM_FIELD_10_OPTION_ID, 12010
  field :ORDER_CUSTOM_FIELD_11_OPTION_ID, 12011
  field :ORDER_CUSTOM_FIELD_12_OPTION_ID, 12012
  field :ORDER_CUSTOM_FIELD_13_OPTION_ID, 12013
  field :ORDER_CUSTOM_FIELD_14_OPTION_ID, 12014
  field :ORDER_CUSTOM_FIELD_0_VALUE, 13000
  field :ORDER_CUSTOM_FIELD_1_VALUE, 13001
  field :ORDER_CUSTOM_FIELD_2_VALUE, 13002
  field :ORDER_CUSTOM_FIELD_3_VALUE, 13003
  field :ORDER_CUSTOM_FIELD_4_VALUE, 13004
  field :ORDER_CUSTOM_FIELD_5_VALUE, 13005
  field :ORDER_CUSTOM_FIELD_6_VALUE, 13006
  field :ORDER_CUSTOM_FIELD_7_VALUE, 13007
  field :ORDER_CUSTOM_FIELD_8_VALUE, 13008
  field :ORDER_CUSTOM_FIELD_9_VALUE, 13009
  field :ORDER_CUSTOM_FIELD_10_VALUE, 13010
  field :ORDER_CUSTOM_FIELD_11_VALUE, 13011
  field :ORDER_CUSTOM_FIELD_12_VALUE, 13012
  field :ORDER_CUSTOM_FIELD_13_VALUE, 13013
  field :ORDER_CUSTOM_FIELD_14_VALUE, 13014
  field :CREATIVE_CUSTOM_FIELD_0_OPTION_ID, 14000
  field :CREATIVE_CUSTOM_FIELD_1_OPTION_ID, 14001
  field :CREATIVE_CUSTOM_FIELD_2_OPTION_ID, 14002
  field :CREATIVE_CUSTOM_FIELD_3_OPTION_ID, 14003
  field :CREATIVE_CUSTOM_FIELD_4_OPTION_ID, 14004
  field :CREATIVE_CUSTOM_FIELD_5_OPTION_ID, 14005
  field :CREATIVE_CUSTOM_FIELD_6_OPTION_ID, 14006
  field :CREATIVE_CUSTOM_FIELD_7_OPTION_ID, 14007
  field :CREATIVE_CUSTOM_FIELD_8_OPTION_ID, 14008
  field :CREATIVE_CUSTOM_FIELD_9_OPTION_ID, 14009
  field :CREATIVE_CUSTOM_FIELD_10_OPTION_ID, 14010
  field :CREATIVE_CUSTOM_FIELD_11_OPTION_ID, 14011
  field :CREATIVE_CUSTOM_FIELD_12_OPTION_ID, 14012
  field :CREATIVE_CUSTOM_FIELD_13_OPTION_ID, 14013
  field :CREATIVE_CUSTOM_FIELD_14_OPTION_ID, 14014
  field :CREATIVE_CUSTOM_FIELD_0_VALUE, 15000
  field :CREATIVE_CUSTOM_FIELD_1_VALUE, 15001
  field :CREATIVE_CUSTOM_FIELD_2_VALUE, 15002
  field :CREATIVE_CUSTOM_FIELD_3_VALUE, 15003
  field :CREATIVE_CUSTOM_FIELD_4_VALUE, 15004
  field :CREATIVE_CUSTOM_FIELD_5_VALUE, 15005
  field :CREATIVE_CUSTOM_FIELD_6_VALUE, 15006
  field :CREATIVE_CUSTOM_FIELD_7_VALUE, 15007
  field :CREATIVE_CUSTOM_FIELD_8_VALUE, 15008
  field :CREATIVE_CUSTOM_FIELD_9_VALUE, 15009
  field :CREATIVE_CUSTOM_FIELD_10_VALUE, 15010
  field :CREATIVE_CUSTOM_FIELD_11_VALUE, 15011
  field :CREATIVE_CUSTOM_FIELD_12_VALUE, 15012
  field :CREATIVE_CUSTOM_FIELD_13_VALUE, 15013
  field :CREATIVE_CUSTOM_FIELD_14_VALUE, 15014
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_0_OPTION_ID, 16000
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_1_OPTION_ID, 16001
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_2_OPTION_ID, 16002
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_3_OPTION_ID, 16003
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_4_OPTION_ID, 16004
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_5_OPTION_ID, 16005
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_6_OPTION_ID, 16006
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_7_OPTION_ID, 16007
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_8_OPTION_ID, 16008
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_9_OPTION_ID, 16009
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_10_OPTION_ID, 16010
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_11_OPTION_ID, 16011
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_12_OPTION_ID, 16012
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_13_OPTION_ID, 16013
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_14_OPTION_ID, 16014
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_0_VALUE, 17000
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_1_VALUE, 17001
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_2_VALUE, 17002
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_3_VALUE, 17003
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_4_VALUE, 17004
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_5_VALUE, 17005
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_6_VALUE, 17006
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_7_VALUE, 17007
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_8_VALUE, 17008
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_9_VALUE, 17009
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_10_VALUE, 17010
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_11_VALUE, 17011
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_12_VALUE, 17012
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_13_VALUE, 17013
  field :BACKFILL_LINE_ITEM_CUSTOM_FIELD_14_VALUE, 17014
  field :BACKFILL_ORDER_CUSTOM_FIELD_0_OPTION_ID, 18000
  field :BACKFILL_ORDER_CUSTOM_FIELD_1_OPTION_ID, 18001
  field :BACKFILL_ORDER_CUSTOM_FIELD_2_OPTION_ID, 18002
  field :BACKFILL_ORDER_CUSTOM_FIELD_3_OPTION_ID, 18003
  field :BACKFILL_ORDER_CUSTOM_FIELD_4_OPTION_ID, 18004
  field :BACKFILL_ORDER_CUSTOM_FIELD_5_OPTION_ID, 18005
  field :BACKFILL_ORDER_CUSTOM_FIELD_6_OPTION_ID, 18006
  field :BACKFILL_ORDER_CUSTOM_FIELD_7_OPTION_ID, 18007
  field :BACKFILL_ORDER_CUSTOM_FIELD_8_OPTION_ID, 18008
  field :BACKFILL_ORDER_CUSTOM_FIELD_9_OPTION_ID, 18009
  field :BACKFILL_ORDER_CUSTOM_FIELD_10_OPTION_ID, 18010
  field :BACKFILL_ORDER_CUSTOM_FIELD_11_OPTION_ID, 18011
  field :BACKFILL_ORDER_CUSTOM_FIELD_12_OPTION_ID, 18012
  field :BACKFILL_ORDER_CUSTOM_FIELD_13_OPTION_ID, 18013
  field :BACKFILL_ORDER_CUSTOM_FIELD_14_OPTION_ID, 18014
  field :BACKFILL_ORDER_CUSTOM_FIELD_0_VALUE, 19000
  field :BACKFILL_ORDER_CUSTOM_FIELD_1_VALUE, 19001
  field :BACKFILL_ORDER_CUSTOM_FIELD_2_VALUE, 19002
  field :BACKFILL_ORDER_CUSTOM_FIELD_3_VALUE, 19003
  field :BACKFILL_ORDER_CUSTOM_FIELD_4_VALUE, 19004
  field :BACKFILL_ORDER_CUSTOM_FIELD_5_VALUE, 19005
  field :BACKFILL_ORDER_CUSTOM_FIELD_6_VALUE, 19006
  field :BACKFILL_ORDER_CUSTOM_FIELD_7_VALUE, 19007
  field :BACKFILL_ORDER_CUSTOM_FIELD_8_VALUE, 19008
  field :BACKFILL_ORDER_CUSTOM_FIELD_9_VALUE, 19009
  field :BACKFILL_ORDER_CUSTOM_FIELD_10_VALUE, 19010
  field :BACKFILL_ORDER_CUSTOM_FIELD_11_VALUE, 19011
  field :BACKFILL_ORDER_CUSTOM_FIELD_12_VALUE, 19012
  field :BACKFILL_ORDER_CUSTOM_FIELD_13_VALUE, 19013
  field :BACKFILL_ORDER_CUSTOM_FIELD_14_VALUE, 19014
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_0_OPTION_ID, 20000
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_1_OPTION_ID, 20001
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_2_OPTION_ID, 20002
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_3_OPTION_ID, 20003
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_4_OPTION_ID, 20004
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_5_OPTION_ID, 20005
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_6_OPTION_ID, 20006
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_7_OPTION_ID, 20007
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_8_OPTION_ID, 20008
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_9_OPTION_ID, 20009
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_10_OPTION_ID, 20010
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_11_OPTION_ID, 20011
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_12_OPTION_ID, 20012
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_13_OPTION_ID, 20013
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_14_OPTION_ID, 20014
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_0_VALUE, 21000
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_1_VALUE, 21001
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_2_VALUE, 21002
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_3_VALUE, 21003
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_4_VALUE, 21004
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_5_VALUE, 21005
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_6_VALUE, 21006
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_7_VALUE, 21007
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_8_VALUE, 21008
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_9_VALUE, 21009
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_10_VALUE, 21010
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_11_VALUE, 21011
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_12_VALUE, 21012
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_13_VALUE, 21013
  field :BACKFILL_CREATIVE_CUSTOM_FIELD_14_VALUE, 21014
  field :CUSTOM_DIMENSION_0_VALUE_ID, 100_000
  field :CUSTOM_DIMENSION_1_VALUE_ID, 100_001
  field :CUSTOM_DIMENSION_2_VALUE_ID, 100_002
  field :CUSTOM_DIMENSION_3_VALUE_ID, 100_003
  field :CUSTOM_DIMENSION_4_VALUE_ID, 100_004
  field :CUSTOM_DIMENSION_5_VALUE_ID, 100_005
  field :CUSTOM_DIMENSION_6_VALUE_ID, 100_006
  field :CUSTOM_DIMENSION_7_VALUE_ID, 100_007
  field :CUSTOM_DIMENSION_8_VALUE_ID, 100_008
  field :CUSTOM_DIMENSION_9_VALUE_ID, 100_009
  field :CUSTOM_DIMENSION_0_VALUE, 101_000
  field :CUSTOM_DIMENSION_1_VALUE, 101_001
  field :CUSTOM_DIMENSION_2_VALUE, 101_002
  field :CUSTOM_DIMENSION_3_VALUE, 101_003
  field :CUSTOM_DIMENSION_4_VALUE, 101_004
  field :CUSTOM_DIMENSION_5_VALUE, 101_005
  field :CUSTOM_DIMENSION_6_VALUE, 101_006
  field :CUSTOM_DIMENSION_7_VALUE, 101_007
  field :CUSTOM_DIMENSION_8_VALUE, 101_008
  field :CUSTOM_DIMENSION_9_VALUE, 101_009
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Metric do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :METRIC_UNSPECIFIED, 0
  field :ACTIVE_USERS, 223
  field :ACTIVE_VIEW_AUDIBLE_AT_START_PERCENT, 445
  field :ACTIVE_VIEW_AUDIBLE_IMPRESSIONS, 659
  field :ACTIVE_VIEW_AUDIBLE_THROUGH_COMPLETION_PERCENT, 446
  field :ACTIVE_VIEW_AUDIBLE_THROUGH_FIRST_QUARTILE_PERCENT, 447
  field :ACTIVE_VIEW_AUDIBLE_THROUGH_MIDPOINT_PERCENT, 448
  field :ACTIVE_VIEW_AUDIBLE_THROUGH_THIRD_QUARTILE_PERCENT, 449
  field :ACTIVE_VIEW_AUDIO_ENABLED_IMPRESSIONS, 660
  field :ACTIVE_VIEW_AUDIO_MEASURABLE_IMPRESSIONS, 661
  field :ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME, 61
  field :ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS, 58
  field :ACTIVE_VIEW_EVER_AUDIBLE_BACKGROUNDED_PERCENT, 450
  field :ACTIVE_VIEW_EVER_AUDIBLE_PERCENT, 451
  field :ACTIVE_VIEW_EVER_BACKGROUNDED_PERCENT, 452
  field :ACTIVE_VIEW_EVER_MUTED_PERCENT, 453
  field :ACTIVE_VIEW_IMPRESSIONS_AUDIBLE_AND_VISIBLIE_AT_COMPLETION, 411
  field :ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, 57
  field :ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_RATE, 60
  field :ACTIVE_VIEW_NON_MEASURABLE_IMPRESSIONS, 662
  field :ACTIVE_VIEW_NON_VIEWABLE_IMPRESSIONS, 663
  field :ACTIVE_VIEW_NON_VIEWABLE_IMPRESSIONS_DISTRIBUTION, 664
  field :ACTIVE_VIEW_PERCENT_AUDIBLE_IMPRESSIONS, 665
  field :ACTIVE_VIEW_PLUS_MEASURABLE_COUNT, 454
  field :ACTIVE_VIEW_REVENUE, 414
  field :ACTIVE_VIEW_UNDETERMINED_IMPRESSIONS_DISTRIBUTION, 666
  field :ACTIVE_VIEW_VIEWABLE_IMPRESSIONS, 56
  field :ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_DISTRIBUTION, 667
  field :ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_RATE, 59
  field :ADSENSE_ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME, 73
  field :ADSENSE_ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS, 70
  field :ADSENSE_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, 69
  field :ADSENSE_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_RATE, 72
  field :ADSENSE_ACTIVE_VIEW_NON_MEASURABLE_IMPRESSIONS, 642
  field :ADSENSE_ACTIVE_VIEW_NON_VIEWABLE_IMPRESSIONS, 643
  field :ADSENSE_ACTIVE_VIEW_NON_VIEWABLE_IMPRESSIONS_DISTRIBUTION, 644
  field :ADSENSE_ACTIVE_VIEW_UNDETERMINED_IMPRESSIONS_DISTRIBUTION, 645
  field :ADSENSE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS, 68
  field :ADSENSE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_DISTRIBUTION, 646
  field :ADSENSE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_RATE, 71
  field :ADSENSE_AVERAGE_ECPM, 26
  field :ADSENSE_CLICKS, 23
  field :ADSENSE_CTR, 24
  field :ADSENSE_IMPRESSIONS, 22
  field :ADSENSE_PERCENT_CLICKS, 28
  field :ADSENSE_PERCENT_IMPRESSIONS, 27
  field :ADSENSE_PERCENT_REVENUE, 29
  field :ADSENSE_PERCENT_REVENUE_WITHOUT_CPD, 30
  field :ADSENSE_RESPONSES_SERVED, 41
  field :ADSENSE_REVENUE, 25
  field :AD_EXCHANGE_ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME, 79
  field :AD_EXCHANGE_ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS, 76
  field :AD_EXCHANGE_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, 75
  field :AD_EXCHANGE_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_RATE, 78
  field :AD_EXCHANGE_ACTIVE_VIEW_NON_MEASURABLE_IMPRESSIONS, 654
  field :AD_EXCHANGE_ACTIVE_VIEW_NON_VIEWABLE_IMPRESSIONS, 655
  field :AD_EXCHANGE_ACTIVE_VIEW_NON_VIEWABLE_IMPRESSIONS_DISTRIBUTION, 656
  field :AD_EXCHANGE_ACTIVE_VIEW_UNDETERMINED_IMPRESSIONS_DISTRIBUTION, 657
  field :AD_EXCHANGE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS, 74
  field :AD_EXCHANGE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_DISTRIBUTION, 658
  field :AD_EXCHANGE_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_RATE, 77
  field :AD_EXCHANGE_AVERAGE_ECPM, 18
  field :AD_EXCHANGE_CLICKS, 15
  field :AD_EXCHANGE_CPC, 244
  field :AD_EXCHANGE_CTR, 16
  field :AD_EXCHANGE_DELIVERY_RATE, 245
  field :AD_EXCHANGE_IMPRESSIONS, 14
  field :AD_EXCHANGE_IMPRESSIONS_PER_AD_VIEWER, 427
  field :AD_EXCHANGE_IMPRESSIONS_PER_SESSION, 428
  field :AD_EXCHANGE_LIFT, 246
  field :AD_EXCHANGE_MATCHED_REQUEST_CTR, 247
  field :AD_EXCHANGE_MATCHED_REQUEST_ECPM, 248
  field :AD_EXCHANGE_MATCH_RATE, 249
  field :AD_EXCHANGE_OPPORTUNITIES_FROM_ERRORS, 250
  field :AD_EXCHANGE_OPPORTUNITIES_FROM_IMPRESSIONS, 251
  field :AD_EXCHANGE_PERCENT_CLICKS, 20
  field :AD_EXCHANGE_PERCENT_IMPRESSIONS, 19
  field :AD_EXCHANGE_PERCENT_REVENUE, 21
  field :AD_EXCHANGE_PERCENT_REVENUE_WITHOUT_CPD, 31
  field :AD_EXCHANGE_PLUS_YIELD_GROUP_ECPM, 252
  field :AD_EXCHANGE_PLUS_YIELD_GROUP_IMPRESSIONS, 253
  field :AD_EXCHANGE_PLUS_YIELD_GROUP_REVENUE, 254
  field :AD_EXCHANGE_RESPONSES_SERVED, 42
  field :AD_EXCHANGE_REVENUE, 17
  field :AD_EXCHANGE_REVENUE_PAID_THROUGH_MCM_AUTOPAYMENT, 212
  field :AD_EXCHANGE_REVENUE_PER_AD_VIEWER, 429
  field :AD_EXCHANGE_TOTAL_REQUESTS, 255
  field :AD_EXCHANGE_TOTAL_REQUEST_CTR, 256
  field :AD_EXCHANGE_TOTAL_REQUEST_ECPM, 257
  field :AD_EXPOSURE_SECONDS, 241
  field :AD_REQUESTS, 38
  field :AD_SERVER_ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME, 67
  field :AD_SERVER_ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS, 64
  field :AD_SERVER_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, 63
  field :AD_SERVER_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_RATE, 66
  field :AD_SERVER_ACTIVE_VIEW_NON_MEASURABLE_IMPRESSIONS, 332
  field :AD_SERVER_ACTIVE_VIEW_NON_VIEWABLE_IMPRESSIONS, 331
  field :AD_SERVER_ACTIVE_VIEW_NON_VIEWABLE_IMPRESSIONS_DISTRIBUTION, 334
  field :AD_SERVER_ACTIVE_VIEW_UNDETERMINED_IMPRESSIONS_DISTRIBUTION, 335
  field :AD_SERVER_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS, 62
  field :AD_SERVER_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_DISTRIBUTION, 333
  field :AD_SERVER_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS_RATE, 65
  field :AD_SERVER_AVERAGE_ECPM, 34
  field :AD_SERVER_AVERAGE_ECPM_WITHOUT_CPD, 10
  field :AD_SERVER_BEGIN_TO_RENDER_IMPRESSIONS, 262
  field :AD_SERVER_CLICKS, 7
  field :AD_SERVER_COMPLETED_VIEWS, 431
  field :AD_SERVER_COVIEWED_IMPRESSIONS, 554
  field :AD_SERVER_CPD_REVENUE, 32
  field :AD_SERVER_CTR, 8
  field :AD_SERVER_GROSS_REVENUE, 483
  field :AD_SERVER_GROSS_REVENUE_WITHOUT_CPD, 484
  field :AD_SERVER_IMPRESSIONS, 6
  field :AD_SERVER_IMPRESSIONS_WITH_COMPANION, 222
  field :AD_SERVER_INACTIVE_BEGIN_TO_RENDER_IMPRESSIONS, 338
  field :AD_SERVER_PERCENT_CLICKS, 12
  field :AD_SERVER_PERCENT_IMPRESSIONS, 11
  field :AD_SERVER_PERCENT_REVENUE, 35
  field :AD_SERVER_PERCENT_REVENUE_WITHOUT_CPD, 13
  field :AD_SERVER_RESPONSES_SERVED, 40
  field :AD_SERVER_REVENUE, 33
  field :AD_SERVER_REVENUE_PAID_THROUGH_MCM_AUTOPAYMENT, 213
  field :AD_SERVER_REVENUE_WITHOUT_CPD, 9
  field :AD_SERVER_TARGETED_CLICKS, 274
  field :AD_SERVER_TARGETED_IMPRESSIONS, 275
  field :AD_SERVER_TRACKED_ADS, 264
  field :AD_SERVER_UNFILTERED_BEGIN_TO_RENDER_IMPRESSIONS, 261
  field :AD_SERVER_UNFILTERED_CLICKS, 259
  field :AD_SERVER_UNFILTERED_DOWNLOADED_IMPRESSIONS, 260
  field :AD_SERVER_UNFILTERED_IMPRESSIONS, 260
  field :AD_SERVER_UNFILTERED_TRACKED_ADS, 263
  field :AD_UNIT_EXPOSURE_SECONDS, 242
  field :AD_VIEWERS, 425
  field :ATN_ADS_FAILED_TO_RENDER, 430
  field :ATN_ELIGIBLE_LINE_ITEMS, 342
  field :ATN_ELIGIBLE_LINE_ITEMS_AD_REQUESTS, 343
  field :ATN_HBT_ALLOWED_AD_REQUESTS, 344
  field :ATN_HBT_BIDS_IN_AUCTION, 345
  field :ATN_HBT_BIDS_IN_AUCTION_AD_REQUESTS, 346
  field :ATN_HBT_CANDIDATE_BIDS, 347
  field :ATN_HBT_INVALID_AD_REQUESTS, 348
  field :ATN_HBT_NO_BIDS_AD_REQUESTS, 472
  field :ATN_HBT_REJECTED_BIDS, 349
  field :ATN_HBT_VALID_AD_REQUESTS, 350
  field :ATN_HBT_WITH_BIDS_AD_REQUESTS, 473
  field :ATN_INVALID_AD_REQUESTS, 351
  field :ATN_LINE_ITEMS_CREATIVE_NOT_RETRIEVED, 476
  field :ATN_LINE_ITEMS_IN_AUCTION, 352
  field :ATN_LINE_ITEMS_NOT_COMPETING, 515
  field :ATN_LINE_ITEMS_NOT_SELECTED, 353
  field :ATN_LINE_ITEM_IN_AUCTION_AD_REQUESTS, 354
  field :ATN_LINE_ITEM_TARGETED_AD_REQUESTS, 355
  field :ATN_MEDIATION_ALLOWED_AD_REQUESTS, 356
  field :ATN_MEDIATION_INVALID_AD_REQUESTS, 357
  field :ATN_MEDIATION_LOADED_ADS_FROM_CHAINS, 358
  field :ATN_MEDIATION_NO_PARTNER_AD_REQUESTS, 474
  field :ATN_MEDIATION_PARTNERS_IN_AUCTION, 359
  field :ATN_MEDIATION_PARTNERS_IN_AUCTION_AD_REQUESTS, 360
  field :ATN_MEDIATION_REJECTED_PARTNERS, 361
  field :ATN_MEDIATION_TARGETED_PARTNERS, 362
  field :ATN_MEDIATION_TOTAL_YIELD_PARTNERS, 442
  field :ATN_MEDIATION_UNLOADED_ADS_FROM_CHAINS, 363
  field :ATN_MEDIATION_UNUSED_BIDS_OR_PARTNERS, 364
  field :ATN_MEDIATION_VALID_AD_REQUESTS, 365
  field :ATN_MEDIATION_WITH_PARTNERS_AD_REQUESTS, 475
  field :ATN_PROGRAMMATIC_AD_REQUESTS_WITH_BIDS, 366
  field :ATN_PROGRAMMATIC_AD_REQUESTS_WITH_BID_REQUESTS_SENT, 367
  field :ATN_PROGRAMMATIC_ALLOWED_AD_REQUESTS, 368
  field :ATN_PROGRAMMATIC_BIDS_IN_AUCTION, 369
  field :ATN_PROGRAMMATIC_BID_IN_AUCTION_AD_REQUESTS, 370
  field :ATN_PROGRAMMATIC_BID_REQUESTS_SENT, 371
  field :ATN_PROGRAMMATIC_BID_REQUESTS_WITH_RESPONSE, 372
  field :ATN_PROGRAMMATIC_BID_REQUEST_CANDIDATES, 373
  field :ATN_PROGRAMMATIC_BID_REQUEST_ERRORS, 374
  field :ATN_PROGRAMMATIC_INELIGIBLE_AD_REQUESTS, 375
  field :ATN_PROGRAMMATIC_REJECTED_BIDS, 376
  field :ATN_PROGRAMMATIC_SKIPPED_BID_REQUESTS, 377
  field :ATN_PROGRAMMATIC_TOTAL_BIDS, 378
  field :ATN_PROGRAMMATIC_VALID_AD_REQUESTS, 379
  field :ATN_REJECTED_LINE_ITEMS, 380
  field :ATN_SERVED_MEDIATION_CHAINS, 381
  field :ATN_SERVED_SINGLE_ADS, 382
  field :ATN_TARGETED_LINE_ITEMS, 383
  field :ATN_TOTAL_AD_REQUESTS, 384
  field :ATN_TOTAL_COMPETING_ADS_IN_AUCTION, 385
  field :ATN_TOTAL_LOADED_ADS, 387
  field :ATN_VALID_AD_REQUESTS, 389
  field :ATN_YIELD_GROUP_MEDIATION_PASSBACKS, 390
  field :AVERAGE_ECPM, 37
  field :AVERAGE_ECPM_WITHOUT_CPD, 5
  field :AVERAGE_ENGAGEMENT_SECONDS_PER_SESSION, 224
  field :AVERAGE_ENGAGEMENT_SECONDS_PER_USER, 225
  field :AVERAGE_IMPRESSIONS_PER_UNIQUE_VISITOR, 418
  field :AVERAGE_PURCHASE_REVENUE_PER_PAYING_USER, 226
  field :AVERAGE_REVENUE_PER_USER, 227
  field :AVERAGE_SESSION_SECONDS, 228
  field :BIDS, 443
  field :BID_AVERAGE_CPM, 444
  field :BOUNCE_RATE, 433
  field :CLICKS, 2
  field :CODE_SERVED_COUNT, 44
  field :CPC_REVENUE, 440
  field :CPM_REVENUE, 441
  field :CREATIVE_LOAD_TIME_0_500_PERCENT, 324
  field :CREATIVE_LOAD_TIME_1000_2000_PERCENT, 326
  field :CREATIVE_LOAD_TIME_2000_4000_PERCENT, 327
  field :CREATIVE_LOAD_TIME_4000_8000_PERCENT, 328
  field :CREATIVE_LOAD_TIME_500_1000_PERCENT, 325
  field :CREATIVE_LOAD_TIME_GT_8000_PERCENT, 329
  field :CTR, 3
  field :DEALS_BIDS, 542
  field :DEALS_BID_RATE, 543
  field :DEALS_BID_REQUESTS, 544
  field :DEALS_WINNING_BIDS, 545
  field :DEALS_WIN_RATE, 546
  field :DOM_LOAD_TO_FIRST_AD_REQUEST_0_500_PERCENT, 521
  field :DOM_LOAD_TO_FIRST_AD_REQUEST_1000_2000_PERCENT, 522
  field :DOM_LOAD_TO_FIRST_AD_REQUEST_2000_4000_PERCENT, 523
  field :DOM_LOAD_TO_FIRST_AD_REQUEST_4000_8000_PERCENT, 524
  field :DOM_LOAD_TO_FIRST_AD_REQUEST_500_1000_PERCENT, 525
  field :DOM_LOAD_TO_FIRST_AD_REQUEST_GT_8000_PERCENT, 520
  field :DOM_LOAD_TO_TAG_LOAD_TIME_0_500_PERCENT, 526
  field :DOM_LOAD_TO_TAG_LOAD_TIME_1000_2000_PERCENT, 527
  field :DOM_LOAD_TO_TAG_LOAD_TIME_2000_4000_PERCENT, 528
  field :DOM_LOAD_TO_TAG_LOAD_TIME_4000_8000_PERCENT, 529
  field :DOM_LOAD_TO_TAG_LOAD_TIME_500_1000_PERCENT, 531
  field :DOM_LOAD_TO_TAG_LOAD_TIME_GT_8000_PERCENT, 530
  field :DROPOFF_RATE, 415
  field :ENGAGED_SESSIONS, 229
  field :ENGAGED_SESSIONS_PER_USER, 230
  field :ENGAGEMENT_RATE, 426
  field :EUROPEAN_REGULATIONS_CONSENT_RATE, 270
  field :EUROPEAN_REGULATIONS_CUSTOM_CONSENT_RATE, 271
  field :EUROPEAN_REGULATIONS_MESSAGES_SHOWN, 272
  field :EUROPEAN_REGULATIONS_NO_CONSENT_RATE, 273
  field :FILL_RATE, 258
  field :GOOGLE_ANALYTICS_CLICKS, 231
  field :GOOGLE_ANALYTICS_CTR, 232
  field :GOOGLE_ANALYTICS_ECPM, 233
  field :GOOGLE_ANALYTICS_IMPRESSIONS, 234
  field :GOOGLE_ANALYTICS_REVENUE, 235
  field :GOOGLE_ANALYTICS_VIEWS, 236
  field :GOOGLE_ANALYTICS_VIEWS_PER_USER, 237
  field :GOOGLE_SOLD_AUCTION_COVIEWED_IMPRESSIONS, 129
  field :GOOGLE_SOLD_AUCTION_IMPRESSIONS, 128
  field :GOOGLE_SOLD_COVIEWED_IMPRESSIONS, 131
  field :GOOGLE_SOLD_IMPRESSIONS, 130
  field :GOOGLE_SOLD_RESERVATION_COVIEWED_IMPRESSIONS, 127
  field :GOOGLE_SOLD_RESERVATION_IMPRESSIONS, 126
  field :IMPRESSIONS, 1
  field :INACTIVE_BEGIN_TO_RENDER_IMPRESSIONS, 407
  field :INVENTORY_SHARES, 547
  field :INVENTORY_SHARE_PARTNER_UNFILLED_OPPORTUNITIES, 548
  field :INVOICED_IMPRESSIONS, 404
  field :INVOICED_UNFILLED_IMPRESSIONS, 405
  field :MEDIATION_CHAINS_FILLED, 584
  field :MUTED_IMPRESSIONS, 412
  field :MUTE_ELIGIBLE_IMPRESSIONS, 409
  field :OPPORTUNITIES, 463
  field :OVERDELIVERED_IMPRESSIONS, 432
  field :PARTNER_SALES_FILLED_POD_REQUESTS, 135
  field :PARTNER_SALES_FILL_RATE, 136
  field :PARTNER_SALES_PARTNER_MATCH_RATE, 137
  field :PARTNER_SALES_QUERIES, 132
  field :PARTNER_SALES_UNFILLED_IMPRESSIONS, 133
  field :PARTNER_SALES_UNMATCHED_QUERIES, 134
  field :PARTNER_SOLD_CODE_SERVED, 125
  field :PARTNER_SOLD_COVIEWED_IMPRESSIONS, 124
  field :PARTNER_SOLD_IMPRESSIONS, 123
  field :PROGRAMMATIC_ELIGIBLE_AD_REQUESTS, 177
  field :PROGRAMMATIC_MATCH_RATE, 178
  field :PROGRAMMATIC_RESPONSES_SERVED, 176
  field :REACH_IMPRESSIONS, 416
  field :RESPONSES_SERVED, 39
  field :RETENTION, 238
  field :REVENUE, 36
  field :REVENUE_PAID_THROUGH_MCM_AUTOPAYMENT, 214
  field :REVENUE_WITHOUT_CPD, 4
  field :REWARDS_GRANTED, 413
  field :RICH_MEDIA_AVERAGE_DISPLAY_TIME, 587
  field :RICH_MEDIA_AVERAGE_INTERACTION_TIME, 588
  field :RICH_MEDIA_BACKUP_IMAGES, 589
  field :RICH_MEDIA_CUSTOM_EVENT_COUNT, 599
  field :RICH_MEDIA_CUSTOM_EVENT_TIME, 600
  field :RICH_MEDIA_DISPLAY_TIME, 590
  field :RICH_MEDIA_EXPANDING_TIME, 591
  field :RICH_MEDIA_EXPANSIONS, 592
  field :RICH_MEDIA_FULL_SCREEN_IMPRESSIONS, 593
  field :RICH_MEDIA_INTERACTION_COUNT, 594
  field :RICH_MEDIA_INTERACTION_RATE, 595
  field :RICH_MEDIA_INTERACTION_TIME, 596
  field :RICH_MEDIA_INTERACTIVE_IMPRESSIONS, 597
  field :RICH_MEDIA_MANUAL_CLOSES, 598
  field :RICH_MEDIA_VIDEO_COMPLETES, 503
  field :RICH_MEDIA_VIDEO_INTERACTIONS, 505
  field :RICH_MEDIA_VIDEO_INTERACTION_RATE, 504
  field :RICH_MEDIA_VIDEO_MIDPOINTS, 506
  field :RICH_MEDIA_VIDEO_MUTES, 507
  field :RICH_MEDIA_VIDEO_PAUSES, 508
  field :RICH_MEDIA_VIDEO_PLAYS, 509
  field :RICH_MEDIA_VIDEO_REPLAYS, 510
  field :RICH_MEDIA_VIDEO_STOPS, 511
  field :RICH_MEDIA_VIDEO_UNMUTES, 512
  field :RICH_MEDIA_VIDEO_VIEW_RATE, 513
  field :RICH_MEDIA_VIDEO_VIEW_TIME, 514
  field :SELL_THROUGH_AVAILABLE_IMPRESSIONS, 477
  field :SELL_THROUGH_FORECASTED_IMPRESSIONS, 478
  field :SELL_THROUGH_RESERVED_IMPRESSIONS, 479
  field :SELL_THROUGH_SELL_THROUGH_RATE, 480
  field :SERVER_SIDE_UNWRAPPING_AVERAGE_LATENCY_MS, 434
  field :SERVER_SIDE_UNWRAPPING_CALLOUTS, 435
  field :SERVER_SIDE_UNWRAPPING_EMPTY_RESPONSES, 436
  field :SERVER_SIDE_UNWRAPPING_ERROR_RESPONSES, 437
  field :SERVER_SIDE_UNWRAPPING_SUCCESSFUL_RESPONSES, 438
  field :SERVER_SIDE_UNWRAPPING_TIMEOUTS, 439
  field :SESSIONS, 239
  field :TAG_LOAD_TO_FIRST_AD_REQUEST_0_500_PERCENT, 455
  field :TAG_LOAD_TO_FIRST_AD_REQUEST_1000_2000_PERCENT, 457
  field :TAG_LOAD_TO_FIRST_AD_REQUEST_2000_4000_PERCENT, 458
  field :TAG_LOAD_TO_FIRST_AD_REQUEST_4000_8000_PERCENT, 459
  field :TAG_LOAD_TO_FIRST_AD_REQUEST_500_1000_PERCENT, 456
  field :TAG_LOAD_TO_FIRST_AD_REQUEST_GT_8000_PERCENT, 460
  field :TARGETED_CLICKS, 276
  field :TARGETED_IMPRESSIONS, 277
  field :UNFILLED_IMPRESSIONS, 45
  field :UNIQUE_VISITORS, 417
  field :UNLOADED_IMPRESSIONS_DUE_TO_CPU, 408
  field :UNLOADED_IMPRESSIONS_DUE_TO_NETWORK, 406
  field :UNMATCHED_AD_REQUESTS, 43
  field :UNVIEWED_REASON_OTHER_PERCENT, 550
  field :UNVIEWED_REASON_SLOT_NEVER_ENTERED_VIEWPORT_PERCENT, 553
  field :UNVIEWED_REASON_USER_SCROLLED_BEFORE_AD_FILLED_PERCENT, 551
  field :UNVIEWED_REASON_USER_SCROLLED_BEFORE_AD_LOADED_PERCENT, 552
  field :UNVIEWED_REASON_USER_SCROLLED_BEFORE_ONE_SECOND_PERCENT, 549
  field :USER_ENGAGEMENT_DURATION_IN_SECONDS, 240
  field :USER_MESSAGES_AD_BLOCKING_EXTENSION_RATE, 486
  field :USER_MESSAGES_AD_BLOCKING_RECOVERY_ALLOWLISTED_COUNT, 487
  field :USER_MESSAGES_AD_BLOCKING_RECOVERY_MESSAGES_SHOWN, 488
  field :USER_MESSAGES_ALLOW_ADS_PAGEVIEWS, 489
  field :USER_MESSAGES_CCPA_MESSAGES_SHOWN, 490
  field :USER_MESSAGES_IDFA_ATT_ALERTS_SHOWN, 491
  field :USER_MESSAGES_IDFA_ATT_CONSENT, 492
  field :USER_MESSAGES_IDFA_ATT_CONSENT_RATE, 493
  field :USER_MESSAGES_IDFA_ATT_DECLINE_CONSENT, 494
  field :USER_MESSAGES_IDFA_ATT_DECLINE_RATE, 495
  field :USER_MESSAGES_IDFA_EXPLAINERS_SHOWN, 496
  field :USER_MESSAGES_IDFA_IAB_MESSAGES_SHOWN, 497
  field :USER_MESSAGES_IDFA_NO_DECISION, 498
  field :USER_MESSAGES_OFFERWALL_MESSAGES_SHOWN, 121
  field :USER_MESSAGES_OFFERWALL_SUCCESSFUL_ENGAGEMENTS, 122
  field :USER_MESSAGES_POST_OFFERWALL_PAGEVIEWS, 499
  field :USER_MESSAGES_TOTAL_ESTIMATED_REVENUE, 500
  field :USER_MESSAGES_UPTC_MESSAGES_SHOWN, 501
  field :USER_MESSAGES_UPTC_PERSONALIZATION_OPT_OUT_RATIO, 502
  field :VIDEO_ERROR_100_COUNT, 180
  field :VIDEO_ERROR_101_COUNT, 181
  field :VIDEO_ERROR_102_COUNT, 182
  field :VIDEO_ERROR_200_COUNT, 183
  field :VIDEO_ERROR_201_COUNT, 184
  field :VIDEO_ERROR_202_COUNT, 185
  field :VIDEO_ERROR_203_COUNT, 186
  field :VIDEO_ERROR_300_COUNT, 187
  field :VIDEO_ERROR_301_COUNT, 188
  field :VIDEO_ERROR_302_COUNT, 189
  field :VIDEO_ERROR_303_COUNT, 190
  field :VIDEO_ERROR_400_COUNT, 191
  field :VIDEO_ERROR_401_COUNT, 192
  field :VIDEO_ERROR_402_COUNT, 193
  field :VIDEO_ERROR_403_COUNT, 194
  field :VIDEO_ERROR_405_COUNT, 195
  field :VIDEO_ERROR_406_COUNT, 196
  field :VIDEO_ERROR_407_COUNT, 197
  field :VIDEO_ERROR_408_COUNT, 198
  field :VIDEO_ERROR_409_COUNT, 199
  field :VIDEO_ERROR_410_COUNT, 200
  field :VIDEO_ERROR_500_COUNT, 201
  field :VIDEO_ERROR_501_COUNT, 202
  field :VIDEO_ERROR_502_COUNT, 203
  field :VIDEO_ERROR_503_COUNT, 204
  field :VIDEO_ERROR_600_COUNT, 205
  field :VIDEO_ERROR_601_COUNT, 206
  field :VIDEO_ERROR_602_COUNT, 207
  field :VIDEO_ERROR_603_COUNT, 208
  field :VIDEO_ERROR_604_COUNT, 209
  field :VIDEO_ERROR_900_COUNT, 210
  field :VIDEO_ERROR_901_COUNT, 211
  field :VIDEO_INTERACTION_AVERAGE_INTERACTION_RATE, 92
  field :VIDEO_INTERACTION_COLLAPSES, 93
  field :VIDEO_INTERACTION_EXPANDS, 95
  field :VIDEO_INTERACTION_FULL_SCREENS, 96
  field :VIDEO_INTERACTION_MUTES, 97
  field :VIDEO_INTERACTION_PAUSES, 98
  field :VIDEO_INTERACTION_RESUMES, 99
  field :VIDEO_INTERACTION_REWINDS, 100
  field :VIDEO_INTERACTION_UNMUTES, 101
  field :VIDEO_INTERACTION_VIDEO_SKIPS, 102
  field :VIDEO_MONETIZABLE_CONTENT_VIEWS, 601
  field :VIDEO_REAL_TIME_CREATIVE_SERVES, 139
  field :VIDEO_REAL_TIME_ERROR_100_COUNT, 143
  field :VIDEO_REAL_TIME_ERROR_101_COUNT, 144
  field :VIDEO_REAL_TIME_ERROR_102_COUNT, 145
  field :VIDEO_REAL_TIME_ERROR_200_COUNT, 146
  field :VIDEO_REAL_TIME_ERROR_201_COUNT, 147
  field :VIDEO_REAL_TIME_ERROR_202_COUNT, 148
  field :VIDEO_REAL_TIME_ERROR_203_COUNT, 149
  field :VIDEO_REAL_TIME_ERROR_300_COUNT, 150
  field :VIDEO_REAL_TIME_ERROR_301_COUNT, 151
  field :VIDEO_REAL_TIME_ERROR_302_COUNT, 152
  field :VIDEO_REAL_TIME_ERROR_303_COUNT, 153
  field :VIDEO_REAL_TIME_ERROR_400_COUNT, 154
  field :VIDEO_REAL_TIME_ERROR_401_COUNT, 155
  field :VIDEO_REAL_TIME_ERROR_402_COUNT, 156
  field :VIDEO_REAL_TIME_ERROR_403_COUNT, 157
  field :VIDEO_REAL_TIME_ERROR_405_COUNT, 158
  field :VIDEO_REAL_TIME_ERROR_406_COUNT, 159
  field :VIDEO_REAL_TIME_ERROR_407_COUNT, 160
  field :VIDEO_REAL_TIME_ERROR_408_COUNT, 161
  field :VIDEO_REAL_TIME_ERROR_409_COUNT, 162
  field :VIDEO_REAL_TIME_ERROR_410_COUNT, 163
  field :VIDEO_REAL_TIME_ERROR_500_COUNT, 164
  field :VIDEO_REAL_TIME_ERROR_501_COUNT, 165
  field :VIDEO_REAL_TIME_ERROR_502_COUNT, 166
  field :VIDEO_REAL_TIME_ERROR_503_COUNT, 167
  field :VIDEO_REAL_TIME_ERROR_600_COUNT, 168
  field :VIDEO_REAL_TIME_ERROR_601_COUNT, 169
  field :VIDEO_REAL_TIME_ERROR_602_COUNT, 170
  field :VIDEO_REAL_TIME_ERROR_603_COUNT, 171
  field :VIDEO_REAL_TIME_ERROR_604_COUNT, 172
  field :VIDEO_REAL_TIME_ERROR_900_COUNT, 173
  field :VIDEO_REAL_TIME_ERROR_901_COUNT, 174
  field :VIDEO_REAL_TIME_IMPRESSIONS, 138
  field :VIDEO_REAL_TIME_MATCHED_QUERIES, 140
  field :VIDEO_REAL_TIME_TOTAL_ERROR_COUNT, 175
  field :VIDEO_REAL_TIME_TOTAL_QUERIES, 142
  field :VIDEO_REAL_TIME_UNMATCHED_QUERIES, 141
  field :VIDEO_VIEWERSHIP_AUTO_PLAYS, 103
  field :VIDEO_VIEWERSHIP_AVERAGE_VIEW_RATE, 104
  field :VIDEO_VIEWERSHIP_AVERAGE_VIEW_TIME, 105
  field :VIDEO_VIEWERSHIP_CLICK_TO_PLAYS, 106
  field :VIDEO_VIEWERSHIP_COMPLETES, 107
  field :VIDEO_VIEWERSHIP_COMPLETION_RATE, 108
  field :VIDEO_VIEWERSHIP_ENGAGED_VIEWS, 109
  field :VIDEO_VIEWERSHIP_FIRST_QUARTILES, 110
  field :VIDEO_VIEWERSHIP_MIDPOINTS, 111
  field :VIDEO_VIEWERSHIP_SKIP_BUTTONS_SHOWN, 112
  field :VIDEO_VIEWERSHIP_STARTS, 113
  field :VIDEO_VIEWERSHIP_THIRD_QUARTILES, 114
  field :VIDEO_VIEWERSHIP_TOTAL_ERROR_COUNT, 115
  field :VIDEO_VIEWERSHIP_TOTAL_ERROR_RATE, 94
  field :VIDEO_VIEWERSHIP_VIDEO_LENGTH, 116
  field :VIDEO_VIEWERSHIP_VIEW_THROUGH_RATE, 117
  field :YIELD_GROUP_AUCTIONS_WON, 80
  field :YIELD_GROUP_BIDS, 81
  field :YIELD_GROUP_BIDS_IN_AUCTION, 82
  field :YIELD_GROUP_CALLOUTS, 83
  field :YIELD_GROUP_ESTIMATED_CPM, 88
  field :YIELD_GROUP_ESTIMATED_REVENUE, 87
  field :YIELD_GROUP_IMPRESSIONS, 85
  field :YIELD_GROUP_MEDIATION_FILL_RATE, 89
  field :YIELD_GROUP_MEDIATION_MATCHED_QUERIES, 86
  field :YIELD_GROUP_MEDIATION_PASSBACKS, 118
  field :YIELD_GROUP_MEDIATION_THIRD_PARTY_ECPM, 90
  field :YIELD_GROUP_REVENUE_PAID_THROUGH_MCM_AUTOPAYMENT, 215
  field :YIELD_GROUP_SUCCESSFUL_RESPONSES, 84
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.TimePeriodColumn do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :TIME_PERIOD_COLUMN_UNSPECIFIED, 0
  field :TIME_PERIOD_COLUMN_DATE, 1
  field :TIME_PERIOD_COLUMN_WEEK, 2
  field :TIME_PERIOD_COLUMN_MONTH, 3
  field :TIME_PERIOD_COLUMN_QUARTER, 4
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.MetricValueType do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :PRIMARY, 0
  field :PRIMARY_PERCENT_OF_TOTAL, 1
  field :COMPARISON, 2
  field :COMPARISON_PERCENT_OF_TOTAL, 3
  field :ABSOLUTE_CHANGE, 4
  field :RELATIVE_CHANGE, 5
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.TimeZoneSource do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :TIME_ZONE_SOURCE_UNSPECIFIED, 0
  field :PUBLISHER, 1
  field :AD_EXCHANGE, 2
  field :UTC, 3
  field :PROVIDED, 4
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.DateRange.RelativeDateRange do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :RELATIVE_DATE_RANGE_UNSPECIFIED, 0
  field :TODAY, 1
  field :YESTERDAY, 2
  field :THIS_WEEK, 3
  field :THIS_WEEK_TO_DATE, 29
  field :THIS_MONTH, 4
  field :THIS_MONTH_TO_DATE, 26
  field :THIS_QUARTER, 5
  field :THIS_QUARTER_TO_DATE, 27
  field :THIS_YEAR, 6
  field :THIS_YEAR_TO_DATE, 28
  field :LAST_WEEK, 7
  field :LAST_MONTH, 8
  field :LAST_QUARTER, 9
  field :LAST_YEAR, 10
  field :LAST_7_DAYS, 11
  field :LAST_30_DAYS, 12
  field :LAST_60_DAYS, 13
  field :LAST_90_DAYS, 14
  field :LAST_180_DAYS, 15
  field :LAST_360_DAYS, 16
  field :LAST_365_DAYS, 17
  field :LAST_3_MONTHS, 18
  field :LAST_6_MONTHS, 19
  field :LAST_12_MONTHS, 20
  field :ALL_AVAILABLE, 21
  field :TOMORROW, 30
  field :NEXT_90_DAYS, 31
  field :NEXT_MONTH, 32
  field :NEXT_3_MONTHS, 33
  field :NEXT_12_MONTHS, 34
  field :NEXT_WEEK, 35
  field :NEXT_QUARTER, 36
  field :TO_END_OF_NEXT_MONTH, 37
  field :PREVIOUS_PERIOD, 22
  field :SAME_PERIOD_PREVIOUS_YEAR, 24
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Filter.Operation do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :IN, 0
  field :NOT_IN, 1
  field :CONTAINS, 2
  field :NOT_CONTAINS, 3
  field :LESS_THAN, 4
  field :LESS_THAN_EQUALS, 5
  field :GREATER_THAN, 6
  field :GREATER_THAN_EQUALS, 7
  field :BETWEEN, 8
  field :MATCHES, 9
  field :NOT_MATCHES, 10
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Field do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  oneof :field, 0

  field :dimension, 1,
    type: Google.Ads.Admanager.V1.ReportDefinition.Dimension,
    enum: true,
    oneof: 0

  field :metric, 2, type: Google.Ads.Admanager.V1.ReportDefinition.Metric, enum: true, oneof: 0
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.DateRange.FixedDateRange do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :start_date, 1, type: Google.Type.Date, json_name: "startDate", deprecated: false
  field :end_date, 2, type: Google.Type.Date, json_name: "endDate", deprecated: false
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.DateRange do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  oneof :date_range_type, 0

  field :fixed, 1,
    type: Google.Ads.Admanager.V1.ReportDefinition.DateRange.FixedDateRange,
    oneof: 0

  field :relative, 2,
    type: Google.Ads.Admanager.V1.ReportDefinition.DateRange.RelativeDateRange,
    enum: true,
    oneof: 0
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Filter.FieldFilter do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :field, 1, type: Google.Ads.Admanager.V1.ReportDefinition.Field, deprecated: false

  field :operation, 2,
    type: Google.Ads.Admanager.V1.ReportDefinition.Filter.Operation,
    enum: true,
    deprecated: false

  field :values, 3, repeated: true, type: Google.Ads.Admanager.V1.ReportValue, deprecated: false

  field :slice, 4,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.Slice,
    deprecated: false

  field :time_period_index, 5,
    proto3_optional: true,
    type: :int32,
    json_name: "timePeriodIndex",
    deprecated: false

  field :metric_value_type, 6,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.MetricValueType,
    json_name: "metricValueType",
    enum: true,
    deprecated: false
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Filter.FilterList do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :filters, 1,
    repeated: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.Filter,
    deprecated: false
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Filter do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  oneof :type, 0

  field :field_filter, 1,
    type: Google.Ads.Admanager.V1.ReportDefinition.Filter.FieldFilter,
    json_name: "fieldFilter",
    oneof: 0

  field :not_filter, 2,
    type: Google.Ads.Admanager.V1.ReportDefinition.Filter,
    json_name: "notFilter",
    oneof: 0

  field :and_filter, 3,
    type: Google.Ads.Admanager.V1.ReportDefinition.Filter.FilterList,
    json_name: "andFilter",
    oneof: 0

  field :or_filter, 4,
    type: Google.Ads.Admanager.V1.ReportDefinition.Filter.FilterList,
    json_name: "orFilter",
    oneof: 0
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Sort do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :field, 1, type: Google.Ads.Admanager.V1.ReportDefinition.Field, deprecated: false
  field :descending, 2, type: :bool, deprecated: false

  field :slice, 3,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.Slice,
    deprecated: false

  field :time_period_index, 4,
    proto3_optional: true,
    type: :int32,
    json_name: "timePeriodIndex",
    deprecated: false

  field :metric_value_type, 5,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.MetricValueType,
    json_name: "metricValueType",
    enum: true,
    deprecated: false
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Slice do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :dimension, 1,
    type: Google.Ads.Admanager.V1.ReportDefinition.Dimension,
    enum: true,
    deprecated: false

  field :value, 2, type: Google.Ads.Admanager.V1.ReportValue, deprecated: false
end

defmodule Google.Ads.Admanager.V1.ReportDefinition.Flag do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :filters, 1,
    repeated: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.Filter,
    deprecated: false

  field :name, 2, type: :string, deprecated: false
end

defmodule Google.Ads.Admanager.V1.ReportDefinition do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :dimensions, 1,
    repeated: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.Dimension,
    enum: true,
    deprecated: false

  field :metrics, 2,
    repeated: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.Metric,
    enum: true,
    deprecated: false

  field :filters, 3,
    repeated: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.Filter,
    deprecated: false

  field :time_zone_source, 20,
    type: Google.Ads.Admanager.V1.ReportDefinition.TimeZoneSource,
    json_name: "timeZoneSource",
    enum: true,
    deprecated: false

  field :time_zone, 4, type: :string, json_name: "timeZone", deprecated: false
  field :currency_code, 5, type: :string, json_name: "currencyCode", deprecated: false

  field :date_range, 6,
    type: Google.Ads.Admanager.V1.ReportDefinition.DateRange,
    json_name: "dateRange",
    deprecated: false

  field :comparison_date_range, 9,
    proto3_optional: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.DateRange,
    json_name: "comparisonDateRange",
    deprecated: false

  field :custom_dimension_key_ids, 7,
    repeated: true,
    type: :int64,
    json_name: "customDimensionKeyIds",
    deprecated: false

  field :line_item_custom_field_ids, 11,
    repeated: true,
    type: :int64,
    json_name: "lineItemCustomFieldIds",
    deprecated: false

  field :order_custom_field_ids, 12,
    repeated: true,
    type: :int64,
    json_name: "orderCustomFieldIds",
    deprecated: false

  field :creative_custom_field_ids, 13,
    repeated: true,
    type: :int64,
    json_name: "creativeCustomFieldIds",
    deprecated: false

  field :report_type, 8,
    type: Google.Ads.Admanager.V1.ReportDefinition.ReportType,
    json_name: "reportType",
    enum: true,
    deprecated: false

  field :time_period_column, 10,
    type: Google.Ads.Admanager.V1.ReportDefinition.TimePeriodColumn,
    json_name: "timePeriodColumn",
    enum: true,
    deprecated: false

  field :flags, 14,
    repeated: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.Flag,
    deprecated: false

  field :sorts, 15,
    repeated: true,
    type: Google.Ads.Admanager.V1.ReportDefinition.Sort,
    deprecated: false
end
