defmodule Google.Ads.Googleads.V8.Enums.ClickTypeEnum.ClickType do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  @type t ::
          integer
          | :UNSPECIFIED
          | :UNKNOWN
          | :APP_DEEPLINK
          | :BREADCRUMBS
          | :BROADBAND_PLAN
          | :CALL_TRACKING
          | :CALLS
          | :CLICK_ON_ENGAGEMENT_AD
          | :GET_DIRECTIONS
          | :LOCATION_EXPANSION
          | :LOCATION_FORMAT_CALL
          | :LOCATION_FORMAT_DIRECTIONS
          | :LOCATION_FORMAT_IMAGE
          | :LOCATION_FORMAT_LANDING_PAGE
          | :LOCATION_FORMAT_MAP
          | :LOCATION_FORMAT_STORE_INFO
          | :LOCATION_FORMAT_TEXT
          | :MOBILE_CALL_TRACKING
          | :OFFER_PRINTS
          | :OTHER
          | :PRODUCT_EXTENSION_CLICKS
          | :PRODUCT_LISTING_AD_CLICKS
          | :SITELINKS
          | :STORE_LOCATOR
          | :URL_CLICKS
          | :VIDEO_APP_STORE_CLICKS
          | :VIDEO_CALL_TO_ACTION_CLICKS
          | :VIDEO_CARD_ACTION_HEADLINE_CLICKS
          | :VIDEO_END_CAP_CLICKS
          | :VIDEO_WEBSITE_CLICKS
          | :VISUAL_SITELINKS
          | :WIRELESS_PLAN
          | :PRODUCT_LISTING_AD_LOCAL
          | :PRODUCT_LISTING_AD_MULTICHANNEL_LOCAL
          | :PRODUCT_LISTING_AD_MULTICHANNEL_ONLINE
          | :PRODUCT_LISTING_ADS_COUPON
          | :PRODUCT_LISTING_AD_TRANSACTABLE
          | :PRODUCT_AD_APP_DEEPLINK
          | :SHOWCASE_AD_CATEGORY_LINK
          | :SHOWCASE_AD_LOCAL_STOREFRONT_LINK
          | :SHOWCASE_AD_ONLINE_PRODUCT_LINK
          | :SHOWCASE_AD_LOCAL_PRODUCT_LINK
          | :PROMOTION_EXTENSION
          | :SWIPEABLE_GALLERY_AD_HEADLINE
          | :SWIPEABLE_GALLERY_AD_SWIPES
          | :SWIPEABLE_GALLERY_AD_SEE_MORE
          | :SWIPEABLE_GALLERY_AD_SITELINK_ONE
          | :SWIPEABLE_GALLERY_AD_SITELINK_TWO
          | :SWIPEABLE_GALLERY_AD_SITELINK_THREE
          | :SWIPEABLE_GALLERY_AD_SITELINK_FOUR
          | :SWIPEABLE_GALLERY_AD_SITELINK_FIVE
          | :HOTEL_PRICE
          | :PRICE_EXTENSION
          | :HOTEL_BOOK_ON_GOOGLE_ROOM_SELECTION
          | :SHOPPING_COMPARISON_LISTING

  field :UNSPECIFIED, 0
  field :UNKNOWN, 1
  field :APP_DEEPLINK, 2
  field :BREADCRUMBS, 3
  field :BROADBAND_PLAN, 4
  field :CALL_TRACKING, 5
  field :CALLS, 6
  field :CLICK_ON_ENGAGEMENT_AD, 7
  field :GET_DIRECTIONS, 8
  field :LOCATION_EXPANSION, 9
  field :LOCATION_FORMAT_CALL, 10
  field :LOCATION_FORMAT_DIRECTIONS, 11
  field :LOCATION_FORMAT_IMAGE, 12
  field :LOCATION_FORMAT_LANDING_PAGE, 13
  field :LOCATION_FORMAT_MAP, 14
  field :LOCATION_FORMAT_STORE_INFO, 15
  field :LOCATION_FORMAT_TEXT, 16
  field :MOBILE_CALL_TRACKING, 17
  field :OFFER_PRINTS, 18
  field :OTHER, 19
  field :PRODUCT_EXTENSION_CLICKS, 20
  field :PRODUCT_LISTING_AD_CLICKS, 21
  field :SITELINKS, 22
  field :STORE_LOCATOR, 23
  field :URL_CLICKS, 25
  field :VIDEO_APP_STORE_CLICKS, 26
  field :VIDEO_CALL_TO_ACTION_CLICKS, 27
  field :VIDEO_CARD_ACTION_HEADLINE_CLICKS, 28
  field :VIDEO_END_CAP_CLICKS, 29
  field :VIDEO_WEBSITE_CLICKS, 30
  field :VISUAL_SITELINKS, 31
  field :WIRELESS_PLAN, 32
  field :PRODUCT_LISTING_AD_LOCAL, 33
  field :PRODUCT_LISTING_AD_MULTICHANNEL_LOCAL, 34
  field :PRODUCT_LISTING_AD_MULTICHANNEL_ONLINE, 35
  field :PRODUCT_LISTING_ADS_COUPON, 36
  field :PRODUCT_LISTING_AD_TRANSACTABLE, 37
  field :PRODUCT_AD_APP_DEEPLINK, 38
  field :SHOWCASE_AD_CATEGORY_LINK, 39
  field :SHOWCASE_AD_LOCAL_STOREFRONT_LINK, 40
  field :SHOWCASE_AD_ONLINE_PRODUCT_LINK, 42
  field :SHOWCASE_AD_LOCAL_PRODUCT_LINK, 43
  field :PROMOTION_EXTENSION, 44
  field :SWIPEABLE_GALLERY_AD_HEADLINE, 45
  field :SWIPEABLE_GALLERY_AD_SWIPES, 46
  field :SWIPEABLE_GALLERY_AD_SEE_MORE, 47
  field :SWIPEABLE_GALLERY_AD_SITELINK_ONE, 48
  field :SWIPEABLE_GALLERY_AD_SITELINK_TWO, 49
  field :SWIPEABLE_GALLERY_AD_SITELINK_THREE, 50
  field :SWIPEABLE_GALLERY_AD_SITELINK_FOUR, 51
  field :SWIPEABLE_GALLERY_AD_SITELINK_FIVE, 52
  field :HOTEL_PRICE, 53
  field :PRICE_EXTENSION, 54
  field :HOTEL_BOOK_ON_GOOGLE_ROOM_SELECTION, 55
  field :SHOPPING_COMPARISON_LISTING, 56
end
defmodule Google.Ads.Googleads.V8.Enums.ClickTypeEnum do
  @moduledoc false
  use Protobuf, syntax: :proto3

  @type t :: %__MODULE__{}

  defstruct []
end
