defmodule Google.Ads.Googleads.V18.Enums.RecommendationTypeEnum.RecommendationType do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.1", syntax: :proto3

  field :UNSPECIFIED, 0
  field :UNKNOWN, 1
  field :CAMPAIGN_BUDGET, 2
  field :KEYWORD, 3
  field :TEXT_AD, 4
  field :TARGET_CPA_OPT_IN, 5
  field :MAXIMIZE_CONVERSIONS_OPT_IN, 6
  field :ENHANCED_CPC_OPT_IN, 7
  field :SEARCH_PARTNERS_OPT_IN, 8
  field :MAXIMIZE_CLICKS_OPT_IN, 9
  field :OPTIMIZE_AD_ROTATION, 10
  field :KEYWORD_MATCH_TYPE, 14
  field :MOVE_UNUSED_BUDGET, 15
  field :FORECASTING_CAMPAIGN_BUDGET, 16
  field :TARGET_ROAS_OPT_IN, 17
  field :RESPONSIVE_SEARCH_AD, 18
  field :MARGINAL_ROI_CAMPAIGN_BUDGET, 19
  field :USE_BROAD_MATCH_KEYWORD, 20
  field :RESPONSIVE_SEARCH_AD_ASSET, 21
  field :UPGRADE_SMART_SHOPPING_CAMPAIGN_TO_PERFORMANCE_MAX, 22
  field :RESPONSIVE_SEARCH_AD_IMPROVE_AD_STRENGTH, 23
  field :DISPLAY_EXPANSION_OPT_IN, 24
  field :UPGRADE_LOCAL_CAMPAIGN_TO_PERFORMANCE_MAX, 25
  field :RAISE_TARGET_CPA_BID_TOO_LOW, 26
  field :FORECASTING_SET_TARGET_ROAS, 27
  field :CALLOUT_ASSET, 28
  field :SITELINK_ASSET, 29
  field :CALL_ASSET, 30
  field :SHOPPING_ADD_AGE_GROUP, 31
  field :SHOPPING_ADD_COLOR, 32
  field :SHOPPING_ADD_GENDER, 33
  field :SHOPPING_ADD_GTIN, 34
  field :SHOPPING_ADD_MORE_IDENTIFIERS, 35
  field :SHOPPING_ADD_SIZE, 36
  field :SHOPPING_ADD_PRODUCTS_TO_CAMPAIGN, 37
  field :SHOPPING_FIX_DISAPPROVED_PRODUCTS, 38
  field :SHOPPING_TARGET_ALL_OFFERS, 39
  field :SHOPPING_FIX_SUSPENDED_MERCHANT_CENTER_ACCOUNT, 40
  field :SHOPPING_FIX_MERCHANT_CENTER_ACCOUNT_SUSPENSION_WARNING, 41
  field :SHOPPING_MIGRATE_REGULAR_SHOPPING_CAMPAIGN_OFFERS_TO_PERFORMANCE_MAX, 42
  field :DYNAMIC_IMAGE_EXTENSION_OPT_IN, 43
  field :RAISE_TARGET_CPA, 44
  field :LOWER_TARGET_ROAS, 45
  field :PERFORMANCE_MAX_OPT_IN, 46
  field :IMPROVE_PERFORMANCE_MAX_AD_STRENGTH, 47
  field :MIGRATE_DYNAMIC_SEARCH_ADS_CAMPAIGN_TO_PERFORMANCE_MAX, 48
  field :FORECASTING_SET_TARGET_CPA, 49
  field :SET_TARGET_CPA, 50
  field :SET_TARGET_ROAS, 51
  field :MAXIMIZE_CONVERSION_VALUE_OPT_IN, 52
  field :IMPROVE_GOOGLE_TAG_COVERAGE, 53
  field :PERFORMANCE_MAX_FINAL_URL_OPT_IN, 54
  field :REFRESH_CUSTOMER_MATCH_LIST, 55
  field :CUSTOM_AUDIENCE_OPT_IN, 56
  field :LEAD_FORM_ASSET, 57
  field :IMPROVE_DEMAND_GEN_AD_STRENGTH, 58
end

defmodule Google.Ads.Googleads.V18.Enums.RecommendationTypeEnum do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.1", syntax: :proto3
end
