defmodule Google.Cloud.Securitycenter.V2.MitreAttack.Tactic do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.1", syntax: :proto3

  field :TACTIC_UNSPECIFIED, 0
  field :RECONNAISSANCE, 1
  field :RESOURCE_DEVELOPMENT, 2
  field :INITIAL_ACCESS, 5
  field :EXECUTION, 3
  field :PERSISTENCE, 6
  field :PRIVILEGE_ESCALATION, 8
  field :DEFENSE_EVASION, 7
  field :CREDENTIAL_ACCESS, 9
  field :DISCOVERY, 10
  field :LATERAL_MOVEMENT, 11
  field :COLLECTION, 12
  field :COMMAND_AND_CONTROL, 4
  field :EXFILTRATION, 13
  field :IMPACT, 14
end

defmodule Google.Cloud.Securitycenter.V2.MitreAttack.Technique do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.14.1", syntax: :proto3

  field :TECHNIQUE_UNSPECIFIED, 0
  field :DATA_OBFUSCATION, 70
  field :DATA_OBFUSCATION_STEGANOGRAPHY, 71
  field :OS_CREDENTIAL_DUMPING, 114
  field :OS_CREDENTIAL_DUMPING_PROC_FILESYSTEM, 115
  field :OS_CREDENTIAL_DUMPING_ETC_PASSWORD_AND_ETC_SHADOW, 122
  field :DATA_FROM_LOCAL_SYSTEM, 117
  field :AUTOMATED_EXFILTRATION, 68
  field :OBFUSCATED_FILES_OR_INFO, 72
  field :STEGANOGRAPHY, 73
  field :COMPILE_AFTER_DELIVERY, 74
  field :COMMAND_OBFUSCATION, 75
  field :SCHEDULED_TRANSFER, 120
  field :SYSTEM_OWNER_USER_DISCOVERY, 118
  field :MASQUERADING, 49
  field :MATCH_LEGITIMATE_NAME_OR_LOCATION, 50
  field :BOOT_OR_LOGON_INITIALIZATION_SCRIPTS, 37
  field :STARTUP_ITEMS, 38
  field :NETWORK_SERVICE_DISCOVERY, 32
  field :SCHEDULED_TASK_JOB, 89
  field :SCHEDULED_TASK_JOB_CRON, 119
  field :CONTAINER_ORCHESTRATION_JOB, 90
  field :PROCESS_INJECTION, 93
  field :INPUT_CAPTURE, 103
  field :INPUT_CAPTURE_KEYLOGGING, 104
  field :PROCESS_DISCOVERY, 56
  field :COMMAND_AND_SCRIPTING_INTERPRETER, 6
  field :UNIX_SHELL, 7
  field :PYTHON, 59
  field :EXPLOITATION_FOR_PRIVILEGE_ESCALATION, 63
  field :PERMISSION_GROUPS_DISCOVERY, 18
  field :CLOUD_GROUPS, 19
  field :INDICATOR_REMOVAL, 123
  field :INDICATOR_REMOVAL_CLEAR_LINUX_OR_MAC_SYSTEM_LOGS, 124
  field :INDICATOR_REMOVAL_CLEAR_COMMAND_HISTORY, 125
  field :INDICATOR_REMOVAL_FILE_DELETION, 64
  field :INDICATOR_REMOVAL_TIMESTOMP, 128
  field :INDICATOR_REMOVAL_CLEAR_MAILBOX_DATA, 126
  field :APPLICATION_LAYER_PROTOCOL, 45
  field :DNS, 46
  field :SOFTWARE_DEPLOYMENT_TOOLS, 47
  field :VALID_ACCOUNTS, 14
  field :DEFAULT_ACCOUNTS, 35
  field :LOCAL_ACCOUNTS, 15
  field :CLOUD_ACCOUNTS, 16
  field :FILE_AND_DIRECTORY_DISCOVERY, 121
  field :ACCOUNT_DISCOVERY_LOCAL_ACCOUNT, 116
  field :PROXY, 9
  field :EXTERNAL_PROXY, 10
  field :MULTI_HOP_PROXY, 11
  field :ACCOUNT_MANIPULATION, 22
  field :ADDITIONAL_CLOUD_CREDENTIALS, 40
  field :ADDITIONAL_CLOUD_ROLES, 67
  field :SSH_AUTHORIZED_KEYS, 23
  field :ADDITIONAL_CONTAINER_CLUSTER_ROLES, 58
  field :MULTI_STAGE_CHANNELS, 76
  field :INGRESS_TOOL_TRANSFER, 3
  field :NATIVE_API, 4
  field :BRUTE_FORCE, 44
  field :AUTOMATED_COLLECTION, 94
  field :SHARED_MODULES, 5
  field :DATA_ENCODING, 77
  field :STANDARD_ENCODING, 78
  field :ACCESS_TOKEN_MANIPULATION, 33
  field :TOKEN_IMPERSONATION_OR_THEFT, 39
  field :CREATE_ACCOUNT, 79
  field :LOCAL_ACCOUNT, 80
  field :DEOBFUSCATE_DECODE_FILES_OR_INFO, 95
  field :EXPLOIT_PUBLIC_FACING_APPLICATION, 27
  field :SUPPLY_CHAIN_COMPROMISE, 129
  field :COMPROMISE_SOFTWARE_DEPENDENCIES_AND_DEVELOPMENT_TOOLS, 130
  field :EXPLOITATION_FOR_CLIENT_EXECUTION, 134
  field :USER_EXECUTION, 69
  field :LINUX_AND_MAC_FILE_AND_DIRECTORY_PERMISSIONS_MODIFICATION, 135
  field :DOMAIN_POLICY_MODIFICATION, 30
  field :DATA_DESTRUCTION, 29
  field :DATA_ENCRYPTED_FOR_IMPACT, 132
  field :SERVICE_STOP, 52
  field :INHIBIT_SYSTEM_RECOVERY, 36
  field :FIRMWARE_CORRUPTION, 81
  field :RESOURCE_HIJACKING, 8
  field :NETWORK_DENIAL_OF_SERVICE, 17
  field :CLOUD_SERVICE_DISCOVERY, 48
  field :STEAL_APPLICATION_ACCESS_TOKEN, 42
  field :ACCOUNT_ACCESS_REMOVAL, 51
  field :TRANSFER_DATA_TO_CLOUD_ACCOUNT, 91
  field :STEAL_WEB_SESSION_COOKIE, 25
  field :CREATE_OR_MODIFY_SYSTEM_PROCESS, 24
  field :EVENT_TRIGGERED_EXECUTION, 65
  field :BOOT_OR_LOGON_AUTOSTART_EXECUTION, 82
  field :KERNEL_MODULES_AND_EXTENSIONS, 83
  field :SHORTCUT_MODIFICATION, 127
  field :ABUSE_ELEVATION_CONTROL_MECHANISM, 34
  field :ABUSE_ELEVATION_CONTROL_MECHANISM_SETUID_AND_SETGID, 136
  field :ABUSE_ELEVATION_CONTROL_MECHANISM_SUDO_AND_SUDO_CACHING, 109
  field :UNSECURED_CREDENTIALS, 13
  field :CREDENTIALS_IN_FILES, 105
  field :BASH_HISTORY, 96
  field :PRIVATE_KEYS, 97
  field :SUBVERT_TRUST_CONTROL, 106
  field :INSTALL_ROOT_CERTIFICATE, 107
  field :COMPROMISE_HOST_SOFTWARE_BINARY, 84
  field :CREDENTIALS_FROM_PASSWORD_STORES, 98
  field :MODIFY_AUTHENTICATION_PROCESS, 28
  field :PLUGGABLE_AUTHENTICATION_MODULES, 108
  field :MULTI_FACTOR_AUTHENTICATION, 137
  field :IMPAIR_DEFENSES, 31
  field :DISABLE_OR_MODIFY_TOOLS, 55
  field :INDICATOR_BLOCKING, 110
  field :DISABLE_OR_MODIFY_LINUX_AUDIT_SYSTEM, 111
  field :HIDE_ARTIFACTS, 85
  field :HIDDEN_FILES_AND_DIRECTORIES, 86
  field :HIDDEN_USERS, 87
  field :EXFILTRATION_OVER_WEB_SERVICE, 20
  field :EXFILTRATION_TO_CLOUD_STORAGE, 21
  field :DYNAMIC_RESOLUTION, 12
  field :LATERAL_TOOL_TRANSFER, 41
  field :HIJACK_EXECUTION_FLOW, 112
  field :HIJACK_EXECUTION_FLOW_DYNAMIC_LINKER_HIJACKING, 113
  field :MODIFY_CLOUD_COMPUTE_INFRASTRUCTURE, 26
  field :CREATE_SNAPSHOT, 54
  field :CLOUD_INFRASTRUCTURE_DISCOVERY, 53
  field :DEVELOP_CAPABILITIES, 99
  field :DEVELOP_CAPABILITIES_MALWARE, 100
  field :OBTAIN_CAPABILITIES, 43
  field :OBTAIN_CAPABILITIES_MALWARE, 101
  field :OBTAIN_CAPABILITIES_VULNERABILITIES, 133
  field :ACTIVE_SCANNING, 1
  field :SCANNING_IP_BLOCKS, 2
  field :STAGE_CAPABILITIES, 88
  field :UPLOAD_MALWARE, 102
  field :CONTAINER_ADMINISTRATION_COMMAND, 60
  field :DEPLOY_CONTAINER, 66
  field :ESCAPE_TO_HOST, 61
  field :CONTAINER_AND_RESOURCE_DISCOVERY, 57
  field :REFLECTIVE_CODE_LOADING, 92
  field :STEAL_OR_FORGE_AUTHENTICATION_CERTIFICATES, 62
  field :FINANCIAL_THEFT, 131
end

defmodule Google.Cloud.Securitycenter.V2.MitreAttack do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.14.1", syntax: :proto3

  field :primary_tactic, 1,
    type: Google.Cloud.Securitycenter.V2.MitreAttack.Tactic,
    json_name: "primaryTactic",
    enum: true

  field :primary_techniques, 2,
    repeated: true,
    type: Google.Cloud.Securitycenter.V2.MitreAttack.Technique,
    json_name: "primaryTechniques",
    enum: true

  field :additional_tactics, 3,
    repeated: true,
    type: Google.Cloud.Securitycenter.V2.MitreAttack.Tactic,
    json_name: "additionalTactics",
    enum: true

  field :additional_techniques, 4,
    repeated: true,
    type: Google.Cloud.Securitycenter.V2.MitreAttack.Technique,
    json_name: "additionalTechniques",
    enum: true

  field :version, 5, type: :string
end
