defmodule Google.Ads.Datamanager.V1.ErrorReason do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :ERROR_REASON_UNSPECIFIED, 0
  field :INTERNAL_ERROR, 1
  field :DEADLINE_EXCEEDED, 2
  field :RESOURCE_EXHAUSTED, 3
  field :NOT_FOUND, 4
  field :PERMISSION_DENIED, 5
  field :INVALID_ARGUMENT, 6
  field :REQUIRED_FIELD_MISSING, 7
  field :INVALID_FORMAT, 8
  field :INVALID_HEX_ENCODING, 9
  field :INVALID_BASE64_ENCODING, 10
  field :INVALID_SHA256_FORMAT, 11
  field :INVALID_POSTAL_CODE, 12
  field :INVALID_COUNTRY_CODE, 13
  field :INVALID_ENUM_VALUE, 14
  field :INVALID_USER_LIST_TYPE, 15
  field :INVALID_AUDIENCE_MEMBER, 16
  field :TOO_MANY_AUDIENCE_MEMBERS, 17
  field :TOO_MANY_USER_IDENTIFIERS, 18
  field :TOO_MANY_DESTINATIONS, 19
  field :INVALID_DESTINATION, 20
  field :DATA_PARTNER_USER_LIST_MUTATE_NOT_ALLOWED, 21
  field :INVALID_MOBILE_ID_FORMAT, 22
  field :INVALID_USER_LIST_ID, 23
  field :MULTIPLE_DATA_TYPES_NOT_ALLOWED, 24
  field :DIFFERENT_LOGIN_ACCOUNTS_NOT_ALLOWED_FOR_DATA_PARTNER, 25
  field :TERMS_AND_CONDITIONS_NOT_SIGNED, 26
  field :INVALID_NUMBER_FORMAT, 27
  field :INVALID_CONVERSION_ACTION_ID, 28
  field :INVALID_CONVERSION_ACTION_TYPE, 29
  field :INVALID_CURRENCY_CODE, 30
  field :INVALID_EVENT, 31
  field :TOO_MANY_EVENTS, 32
  field :DESTINATION_ACCOUNT_NOT_ENABLED_ENHANCED_CONVERSIONS_FOR_LEADS, 33
  field :DESTINATION_ACCOUNT_DATA_POLICY_PROHIBITS_ENHANCED_CONVERSIONS, 34
  field :DESTINATION_ACCOUNT_ENHANCED_CONVERSIONS_TERMS_NOT_SIGNED, 35
  field :DUPLICATE_DESTINATION_REFERENCE, 36
  field :NO_IDENTIFIERS_PROVIDED, 39
  field :INVALID_REQUEST_ID, 48
end
