defmodule Google.Ads.Googleads.V22.Errors.AssetGenerationErrorEnum.AssetGenerationError do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :UNSPECIFIED, 0
  field :UNKNOWN, 1
  field :NO_ASSETS_GENERATED, 2
  field :FINAL_URL_REQUIRED, 3
  field :GENERATION_CONTEXT_MISSING_FINAL_URL, 4
  field :FINAL_URL_SENSITIVE, 5
  field :FINAL_URL_UNSUPPORTED_LANGUAGE, 6
  field :FINAL_URL_UNAVAILABLE, 7
  field :CAMPAIGN_TYPE_REQUIRED, 8
  field :UNSUPPORTED_CAMPAIGN_TYPE, 9
  field :UNSUPPORTED_FIELD_TYPE, 10
  field :UNSUPPORTED_FIELD_TYPE_FOR_CAMPAIGN_TYPE, 11
  field :FREEFORM_PROMPT_UNSUPPORTED_LANGUAGE, 12
  field :FREEFORM_PROMPT_SENSITIVE, 13
  field :INPUT_IMAGE_FILE_SIZE_TOO_LARGE, 14
  field :INPUT_IMAGE_EMPTY, 15
  field :GENERATION_TYPE_REQUIRED, 16
  field :TOO_MANY_KEYWORDS, 17
  field :KEYWORD_INVALID_LENGTH, 18
  field :NO_VALID_KEYWORDS, 19
  field :FREEFORM_PROMPT_INVALID_LENGTH, 20
  field :FREEFORM_PROMPT_REFERENCES_CHILDREN, 21
  field :FREEFORM_PROMPT_REFERENCES_SPECIFIC_PEOPLE, 22
  field :FREEFORM_PROMPT_VIOLATES_ADS_POLICY, 23
  field :FREEFORM_PROMPT_BRAND_CONTENT, 24
  field :INPUT_IMAGE_DEPICTS_CHILDREN, 25
  field :INPUT_IMAGE_CONTAINS_BRAND_CONTENT, 26
  field :INPUT_IMAGE_SENSITIVE, 27
  field :INPUT_IMAGE_VIOLATES_POLICY, 28
  field :ALL_OUTPUT_IMAGES_FILTERED_OUT_CHILDREN_DEPICTION, 29
  field :ALL_OUTPUT_IMAGES_FILTERED_OUT_SPECIFIC_PEOPLE, 30
  field :ALL_OUTPUT_IMAGES_FILTERED_OUT, 31
  field :INPUT_IMAGE_REQUIRED, 32
  field :INPUT_IMAGE_UNSUPPORTED_IMAGE_TYPE, 33
  field :CONTEXT_ASSET_GROUP_NOT_FOUND, 34
  field :CONTEXT_AD_GROUP_AD_NOT_FOUND, 35
  field :CONTEXT_CAMPAIGN_NOT_FOUND, 36
end

defmodule Google.Ads.Googleads.V22.Errors.AssetGenerationErrorEnum do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.15.0", syntax: :proto3
end
