defmodule Google.Ads.Googleads.V18.Errors.RecommendationErrorEnum.RecommendationError do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.13.0", syntax: :proto3

  field :UNSPECIFIED, 0
  field :UNKNOWN, 1
  field :BUDGET_AMOUNT_TOO_SMALL, 2
  field :BUDGET_AMOUNT_TOO_LARGE, 3
  field :INVALID_BUDGET_AMOUNT, 4
  field :POLICY_ERROR, 5
  field :INVALID_BID_AMOUNT, 6
  field :ADGROUP_KEYWORD_LIMIT, 7
  field :RECOMMENDATION_ALREADY_APPLIED, 8
  field :RECOMMENDATION_INVALIDATED, 9
  field :TOO_MANY_OPERATIONS, 10
  field :NO_OPERATIONS, 11
  field :DIFFERENT_TYPES_NOT_SUPPORTED, 12
  field :DUPLICATE_RESOURCE_NAME, 13
  field :RECOMMENDATION_ALREADY_DISMISSED, 14
  field :INVALID_APPLY_REQUEST, 15
  field :RECOMMENDATION_TYPE_APPLY_NOT_SUPPORTED, 17
  field :INVALID_MULTIPLIER, 18
  field :ADVERTISING_CHANNEL_TYPE_GENERATE_NOT_SUPPORTED, 19
  field :RECOMMENDATION_TYPE_GENERATE_NOT_SUPPORTED, 20
  field :RECOMMENDATION_TYPES_CANNOT_BE_EMPTY, 21
  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_REQUIRES_BIDDING_INFO, 22
  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_REQUIRES_BIDDING_STRATEGY_TYPE, 23
  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_REQUIRES_ASSET_GROUP_INFO, 24
  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_REQUIRES_ASSET_GROUP_INFO_WITH_FINAL_URL, 25
  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_REQUIRES_COUNTRY_CODES_FOR_SEARCH_CHANNEL, 26
  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_INVALID_COUNTRY_CODE_FOR_SEARCH_CHANNEL, 27
  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_REQUIRES_LANGUAGE_CODES_FOR_SEARCH_CHANNEL, 28

  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_REQUIRES_EITHER_POSITIVE_OR_NEGATIVE_LOCATION_IDS_FOR_SEARCH_CHANNEL,
        29

  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_REQUIRES_AD_GROUP_INFO_FOR_SEARCH_CHANNEL, 30
  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_REQUIRES_KEYWORDS_FOR_SEARCH_CHANNEL, 31

  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_WITH_CHANNEL_TYPE_SEARCH_AND_BIDDING_STRATEGY_TYPE_TARGET_IMPRESSION_SHARE_REQUIRES_LOCATION,
        32

  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_WITH_CHANNEL_TYPE_SEARCH_AND_BIDDING_STRATEGY_TYPE_TARGET_IMPRESSION_SHARE_REQUIRES_TARGET_IMPRESSION_SHARE_MICROS,
        33

  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_TARGET_IMPRESSION_SHARE_MICROS_BETWEEN_1_AND_1000000,
        34

  field :CAMPAIGN_BUDGET_RECOMMENDATION_TYPE_WITH_CHANNEL_TYPE_SEARCH_AND_BIDDING_STRATEGY_TYPE_TARGET_IMPRESSION_SHARE_REQUIRES_TARGET_IMPRESSION_SHARE_INFO,
        35
end

defmodule Google.Ads.Googleads.V18.Errors.RecommendationErrorEnum do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.13.0", syntax: :proto3
end